// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/screens/bookshelf_continue_reading_fix_verification_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:novel_app/controllers/chapter_list/chapter_loader.dart' as _i5;
import 'package:novel_app/core/interfaces/repositories/i_novel_repository.dart'
    as _i3;
import 'package:novel_app/models/chapter.dart' as _i6;
import 'package:novel_app/models/novel.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNovel_0 extends _i1.SmartFake implements _i2.Novel {
  _FakeNovel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [INovelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockINovelRepository extends _i1.Mock implements _i3.INovelRepository {
  MockINovelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> addToBookshelf(_i2.Novel? novel) => (super.noSuchMethod(
        Invocation.method(
          #addToBookshelf,
          [novel],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> removeFromBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeFromBookshelf,
          [novelUrl],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i2.Novel>> getNovels() => (super.noSuchMethod(
        Invocation.method(
          #getNovels,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Novel>>.value(<_i2.Novel>[]),
      ) as _i4.Future<List<_i2.Novel>>);

  @override
  _i4.Future<bool> isInBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #isInBookshelf,
          [novelUrl],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> updateLastReadChapter(
    String? novelUrl,
    int? chapterIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastReadChapter,
          [
            novelUrl,
            chapterIndex,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> updateTitle(
    String? novelUrl,
    String? newTitle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTitle,
          [
            novelUrl,
            newTitle,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> updateBackgroundSetting(
    String? novelUrl,
    String? backgroundSetting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSetting,
          [
            novelUrl,
            backgroundSetting,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<String?> getBackgroundSetting(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackgroundSetting,
          [novelUrl],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<int> getLastReadChapter(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #getLastReadChapter,
          [novelUrl],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i2.Novel?> getNovelByTitle(String? title) => (super.noSuchMethod(
        Invocation.method(
          #getNovelByTitle,
          [title],
        ),
        returnValue: _i4.Future<_i2.Novel?>.value(),
      ) as _i4.Future<_i2.Novel?>);

  @override
  _i4.Future<_i2.Novel> createNovel({
    required String? title,
    required String? author,
    String? description,
    String? coverUrl,
    String? backgroundSetting,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNovel,
          [],
          {
            #title: title,
            #author: author,
            #description: description,
            #coverUrl: coverUrl,
            #backgroundSetting: backgroundSetting,
          },
        ),
        returnValue: _i4.Future<_i2.Novel>.value(_FakeNovel_0(
          this,
          Invocation.method(
            #createNovel,
            [],
            {
              #title: title,
              #author: author,
              #description: description,
              #coverUrl: coverUrl,
              #backgroundSetting: backgroundSetting,
            },
          ),
        )),
      ) as _i4.Future<_i2.Novel>);

  @override
  _i4.Future<_i2.Novel?> getNovelById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getNovelById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Novel?>.value(),
      ) as _i4.Future<_i2.Novel?>);

  @override
  _i4.Future<String?> getNovelUrlById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getNovelUrlById,
          [id],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<int> updateBackgroundSettingById(
    int? id,
    String? setting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSettingById,
          [
            id,
            setting,
          ],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [ChapterLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockChapterLoader extends _i1.Mock implements _i5.ChapterLoader {
  MockChapterLoader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initApi() => (super.noSuchMethod(
        Invocation.method(
          #initApi,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Chapter>> loadChapters(
    String? novelUrl, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadChapters,
          [novelUrl],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<List<_i6.Chapter>>.value(<_i6.Chapter>[]),
      ) as _i4.Future<List<_i6.Chapter>>);

  @override
  _i4.Future<List<_i6.Chapter>> refreshFromBackend(
    String? novelUrl, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshFromBackend,
          [novelUrl],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i4.Future<List<_i6.Chapter>>.value(<_i6.Chapter>[]),
      ) as _i4.Future<List<_i6.Chapter>>);

  @override
  _i4.Future<int> loadLastReadChapter(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #loadLastReadChapter,
          [novelUrl],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
