// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/screens/bookshelf_continue_reading_cache_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:novel_app/core/interfaces/i_database_connection.dart' as _i7;
import 'package:novel_app/core/interfaces/repositories/i_novel_repository.dart'
    as _i4;
import 'package:novel_app/models/ai_accompaniment_settings.dart' as _i2;
import 'package:novel_app/models/novel.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAiAccompanimentSettings_0 extends _i1.SmartFake
    implements _i2.AiAccompanimentSettings {
  _FakeAiAccompanimentSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [INovelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockINovelRepository extends _i1.Mock implements _i4.INovelRepository {
  MockINovelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> addToBookshelf(_i6.Novel? novel) => (super.noSuchMethod(
        Invocation.method(
          #addToBookshelf,
          [novel],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> removeFromBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeFromBookshelf,
          [novelUrl],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i6.Novel>> getNovels() => (super.noSuchMethod(
        Invocation.method(
          #getNovels,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Novel>>.value(<_i6.Novel>[]),
      ) as _i5.Future<List<_i6.Novel>>);

  @override
  _i5.Future<bool> isInBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #isInBookshelf,
          [novelUrl],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> updateLastReadChapter(
    String? novelUrl,
    int? chapterIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastReadChapter,
          [
            novelUrl,
            chapterIndex,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> updateBackgroundSetting(
    String? novelUrl,
    String? backgroundSetting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSetting,
          [
            novelUrl,
            backgroundSetting,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String?> getBackgroundSetting(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackgroundSetting,
          [novelUrl],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<int> getLastReadChapter(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #getLastReadChapter,
          [novelUrl],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i2.AiAccompanimentSettings> getAiAccompanimentSettings(
          String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAiAccompanimentSettings,
          [novelUrl],
        ),
        returnValue: _i5.Future<_i2.AiAccompanimentSettings>.value(
            _FakeAiAccompanimentSettings_0(
          this,
          Invocation.method(
            #getAiAccompanimentSettings,
            [novelUrl],
          ),
        )),
      ) as _i5.Future<_i2.AiAccompanimentSettings>);

  @override
  _i5.Future<int> updateAiAccompanimentSettings(
    String? novelUrl,
    _i2.AiAccompanimentSettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAiAccompanimentSettings,
          [
            novelUrl,
            settings,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}

/// A class which mocks [IDatabaseConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDatabaseConnection extends _i1.Mock
    implements _i7.IDatabaseConnection {
  MockIDatabaseConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i3.Database>.value(_FakeDatabase_1(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i3.Database>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
