// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/controllers/chapter_reorder_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:novel_app/models/chapter.dart' as _i7;
import 'package:novel_app/models/character.dart' as _i3;
import 'package:novel_app/models/chat_scene.dart' as _i12;
import 'package:novel_app/models/novel.dart' as _i6;
import 'package:novel_app/models/outline.dart' as _i11;
import 'package:novel_app/models/scene_illustration.dart' as _i10;
import 'package:novel_app/models/search_result.dart' as _i8;
import 'package:novel_app/services/database_service.dart' as _i4;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCharacter_1 extends _i1.SmartFake implements _i3.Character {
  _FakeCharacter_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i4.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isWebPlatform => (super.noSuchMethod(
        Invocation.getter(#isWebPlatform),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<int> addToBookshelf(_i6.Novel? novel) => (super.noSuchMethod(
        Invocation.method(
          #addToBookshelf,
          [novel],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> removeFromBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeFromBookshelf,
          [novelUrl],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i6.Novel>> getBookshelf() => (super.noSuchMethod(
        Invocation.method(
          #getBookshelf,
          [],
        ),
        returnValue: _i5.Future<List<_i6.Novel>>.value(<_i6.Novel>[]),
      ) as _i5.Future<List<_i6.Novel>>);

  @override
  _i5.Future<bool> isInBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #isInBookshelf,
          [novelUrl],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> updateLastReadChapter(
    String? novelUrl,
    int? chapterIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastReadChapter,
          [
            novelUrl,
            chapterIndex,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> updateBackgroundSetting(
    String? novelUrl,
    String? backgroundSetting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSetting,
          [
            novelUrl,
            backgroundSetting,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String?> getBackgroundSetting(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackgroundSetting,
          [novelUrl],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<int> getLastReadChapter(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #getLastReadChapter,
          [novelUrl],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> isChapterCached(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isChapterCached,
          [chapterUrl],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<String>> filterUncachedChapters(List<String>? chapterUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterUncachedChapters,
          [chapterUrls],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  void markAsPreloading(String? chapterUrl) => super.noSuchMethod(
        Invocation.method(
          #markAsPreloading,
          [chapterUrl],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isPreloading(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isPreloading,
          [chapterUrl],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearMemoryState() => super.noSuchMethod(
        Invocation.method(
          #clearMemoryState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<int> cacheChapter(
    String? novelUrl,
    _i7.Chapter? chapter,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheChapter,
          [
            novelUrl,
            chapter,
            content,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> updateChapterContent(
    String? chapterUrl,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChapterContent,
          [
            chapterUrl,
            content,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> deleteChapterCache(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteChapterCache,
          [chapterUrl],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String?> getCachedChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapter,
          [chapterUrl],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<List<_i7.Chapter>> getCachedChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapters,
          [novelUrl],
        ),
        returnValue: _i5.Future<List<_i7.Chapter>>.value(<_i7.Chapter>[]),
      ) as _i5.Future<List<_i7.Chapter>>);

  @override
  _i5.Future<int> deleteCachedChapters(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteCachedChapters,
          [novelUrl],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> clearNovelCache(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #clearNovelCache,
          [novelUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getNovelCacheStats(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNovelCacheStats,
          [novelUrl],
        ),
        returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i5.Future<Map<String, int>>);

  @override
  _i5.Future<void> cacheWholeNovel(
    String? novelUrl,
    List<_i7.Chapter>? chapters,
    _i5.Future<String> Function(String)? getContent,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWholeNovel,
          [
            novelUrl,
            chapters,
            getContent,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cacheNovelChapters(
    String? novelUrl,
    List<_i7.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheNovelChapters,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.Chapter>> getCachedNovelChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNovelChapters,
          [novelUrl],
        ),
        returnValue: _i5.Future<List<_i7.Chapter>>.value(<_i7.Chapter>[]),
      ) as _i5.Future<List<_i7.Chapter>>);

  @override
  _i5.Future<void> insertUserChapter(
    String? novelUrl,
    String? title,
    String? content,
    int? insertIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertUserChapter,
          [
            novelUrl,
            title,
            content,
            insertIndex,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> createCustomNovel(
    String? title,
    String? author, {
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomNovel,
          [
            title,
            author,
          ],
          {#description: description},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> createCustomChapter(
    String? novelUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomChapter,
          [
            novelUrl,
            title,
            content,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> updateChaptersOrder(
    String? novelUrl,
    List<_i7.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChaptersOrder,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getCustomChapterContent(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomChapterContent,
          [chapterUrl],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> updateCustomChapter(
    String? chapterUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomChapter,
          [
            chapterUrl,
            title,
            content,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteCustomChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomChapter,
          [chapterUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i8.ChapterSearchResult>> searchInCachedContent(
    String? keyword, {
    String? novelUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchInCachedContent,
          [keyword],
          {#novelUrl: novelUrl},
        ),
        returnValue: _i5.Future<List<_i8.ChapterSearchResult>>.value(
            <_i8.ChapterSearchResult>[]),
      ) as _i5.Future<List<_i8.ChapterSearchResult>>);

  @override
  _i5.Future<List<_i8.CachedNovelInfo>> getCachedNovels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNovels,
          [],
        ),
        returnValue: _i5.Future<List<_i8.CachedNovelInfo>>.value(
            <_i8.CachedNovelInfo>[]),
      ) as _i5.Future<List<_i8.CachedNovelInfo>>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateNovelInBookshelf(_i6.Novel? novel) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNovelInBookshelf,
          [novel],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearBookshelfCache() => (super.noSuchMethod(
        Invocation.method(
          #clearBookshelfCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getCachedChaptersCount(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChaptersCount,
          [novelUrl],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i7.Chapter?> getChapterByUrl(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapterByUrl,
          [chapterUrl],
        ),
        returnValue: _i5.Future<_i7.Chapter?>.value(),
      ) as _i5.Future<_i7.Chapter?>);

  @override
  _i5.Future<void> deleteUserChapter(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteUserChapter,
          [chapterUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateReadingProgress(
    String? novelUrl,
    int? chapterIndex,
    double? progress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReadingProgress,
          [
            novelUrl,
            chapterIndex,
            progress,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> createCharacter(_i3.Character? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCharacter,
          [character],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i3.Character>> getCharacters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacters,
          [novelUrl],
        ),
        returnValue: _i5.Future<List<_i3.Character>>.value(<_i3.Character>[]),
      ) as _i5.Future<List<_i3.Character>>);

  @override
  _i5.Future<_i3.Character?> getCharacter(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getCharacter,
          [id],
        ),
        returnValue: _i5.Future<_i3.Character?>.value(),
      ) as _i5.Future<_i3.Character?>);

  @override
  _i5.Future<int> updateCharacter(_i3.Character? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacter,
          [character],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> deleteCharacter(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCharacter,
          [id],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i3.Character?> findCharacterByName(
    String? novelUrl,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCharacterByName,
          [
            novelUrl,
            name,
          ],
        ),
        returnValue: _i5.Future<_i3.Character?>.value(),
      ) as _i5.Future<_i3.Character?>);

  @override
  _i5.Future<_i3.Character> updateOrInsertCharacter(
          _i3.Character? newCharacter) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrInsertCharacter,
          [newCharacter],
        ),
        returnValue: _i5.Future<_i3.Character>.value(_FakeCharacter_1(
          this,
          Invocation.method(
            #updateOrInsertCharacter,
            [newCharacter],
          ),
        )),
      ) as _i5.Future<_i3.Character>);

  @override
  _i5.Future<List<_i3.Character>> batchUpdateCharacters(
          List<_i3.Character>? newCharacters) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateCharacters,
          [newCharacters],
        ),
        returnValue: _i5.Future<List<_i3.Character>>.value(<_i3.Character>[]),
      ) as _i5.Future<List<_i3.Character>>);

  @override
  _i5.Future<List<String>> getCharacterNames(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterNames,
          [novelUrl],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<bool> characterExists(int? id) => (super.noSuchMethod(
        Invocation.method(
          #characterExists,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i3.Character>> getCharactersByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharactersByIds,
          [ids],
        ),
        returnValue: _i5.Future<List<_i3.Character>>.value(<_i3.Character>[]),
      ) as _i5.Future<List<_i3.Character>>);

  @override
  _i5.Future<int> deleteAllCharacters(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllCharacters,
          [novelUrl],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> updateCharacterCachedImage(
    int? characterId,
    String? imageUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterCachedImage,
          [
            characterId,
            imageUrl,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> clearCharacterCachedImage(int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCharacterCachedImage,
          [characterId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> clearAllCharacterCachedImages(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearAllCharacterCachedImages,
          [novelUrl],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i7.Chapter>> getChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapters,
          [novelUrl],
        ),
        returnValue: _i5.Future<List<_i7.Chapter>>.value(<_i7.Chapter>[]),
      ) as _i5.Future<List<_i7.Chapter>>);

  @override
  _i5.Future<String> getChapterContent(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapterContent,
          [chapterUrl],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getChapterContent,
            [chapterUrl],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> getCachedChapterContent(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapterContent,
          [chapterUrl],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getCachedChapterContent,
            [chapterUrl],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String?> getCharacterCachedImage(int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterCachedImage,
          [characterId],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<int> updateCharacterAvatar(
    int? characterId, {
    String? imageUrl,
    String? originalFilename,
    String? originalImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterAvatar,
          [characterId],
          {
            #imageUrl: imageUrl,
            #originalFilename: originalFilename,
            #originalImageUrl: originalImageUrl,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> hasCharacterAvatar(int? characterId) => (super.noSuchMethod(
        Invocation.method(
          #hasCharacterAvatar,
          [characterId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> insertSceneIllustration(
          _i10.SceneIllustration? illustration) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSceneIllustration,
          [illustration],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> updateSceneIllustrationStatus(
    int? id,
    String? status, {
    List<String>? images,
    String? prompts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSceneIllustrationStatus,
          [
            id,
            status,
          ],
          {
            #images: images,
            #prompts: prompts,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i10.SceneIllustration>> getSceneIllustrationsByChapter(
    String? novelUrl,
    String? chapterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationsByChapter,
          [
            novelUrl,
            chapterId,
          ],
        ),
        returnValue: _i5.Future<List<_i10.SceneIllustration>>.value(
            <_i10.SceneIllustration>[]),
      ) as _i5.Future<List<_i10.SceneIllustration>>);

  @override
  _i5.Future<_i10.SceneIllustration?> getSceneIllustrationByTaskId(
          String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationByTaskId,
          [taskId],
        ),
        returnValue: _i5.Future<_i10.SceneIllustration?>.value(),
      ) as _i5.Future<_i10.SceneIllustration?>);

  @override
  _i5.Future<Map<String, dynamic>> getSceneIllustrationsPaginated({
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationsPaginated,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<int> deleteSceneIllustration(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSceneIllustration,
          [id],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> deleteSceneIllustrationsByChapter(
    String? novelUrl,
    String? chapterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSceneIllustrationsByChapter,
          [
            novelUrl,
            chapterId,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i10.SceneIllustration>> getPendingSceneIllustrations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSceneIllustrations,
          [],
        ),
        returnValue: _i5.Future<List<_i10.SceneIllustration>>.value(
            <_i10.SceneIllustration>[]),
      ) as _i5.Future<List<_i10.SceneIllustration>>);

  @override
  _i5.Future<int> batchUpdateSceneIllustrations(
    List<int>? ids,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateSceneIllustrations,
          [
            ids,
            status,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> saveOutline(_i11.Outline? outline) => (super.noSuchMethod(
        Invocation.method(
          #saveOutline,
          [outline],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i11.Outline?> getOutlineByNovelUrl(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOutlineByNovelUrl,
          [novelUrl],
        ),
        returnValue: _i5.Future<_i11.Outline?>.value(),
      ) as _i5.Future<_i11.Outline?>);

  @override
  _i5.Future<List<_i11.Outline>> getAllOutlines() => (super.noSuchMethod(
        Invocation.method(
          #getAllOutlines,
          [],
        ),
        returnValue: _i5.Future<List<_i11.Outline>>.value(<_i11.Outline>[]),
      ) as _i5.Future<List<_i11.Outline>>);

  @override
  _i5.Future<int> deleteOutline(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteOutline,
          [novelUrl],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> updateOutlineContent(
    String? novelUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOutlineContent,
          [
            novelUrl,
            title,
            content,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> insertChatScene(_i12.ChatScene? scene) => (super.noSuchMethod(
        Invocation.method(
          #insertChatScene,
          [scene],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> updateChatScene(_i12.ChatScene? scene) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatScene,
          [scene],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteChatScene(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteChatScene,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i12.ChatScene>> getAllChatScenes() => (super.noSuchMethod(
        Invocation.method(
          #getAllChatScenes,
          [],
        ),
        returnValue: _i5.Future<List<_i12.ChatScene>>.value(<_i12.ChatScene>[]),
      ) as _i5.Future<List<_i12.ChatScene>>);

  @override
  _i5.Future<_i12.ChatScene?> getChatSceneById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getChatSceneById,
          [id],
        ),
        returnValue: _i5.Future<_i12.ChatScene?>.value(),
      ) as _i5.Future<_i12.ChatScene?>);

  @override
  _i5.Future<List<_i12.ChatScene>> searchChatScenes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchChatScenes,
          [query],
        ),
        returnValue: _i5.Future<List<_i12.ChatScene>>.value(<_i12.ChatScene>[]),
      ) as _i5.Future<List<_i12.ChatScene>>);
}
