// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/bug/custom_novel_init_failure_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i12;
import 'dart:typed_data' as _i11;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:novel_api/novel_api.dart' as _i2;
import 'package:novel_app/core/interfaces/repositories/i_chapter_repository.dart'
    as _i13;
import 'package:novel_app/core/interfaces/repositories/i_novel_repository.dart'
    as _i15;
import 'package:novel_app/models/ai_accompaniment_settings.dart' as _i6;
import 'package:novel_app/models/chapter.dart' as _i9;
import 'package:novel_app/models/chapter_content_result.dart' as _i5;
import 'package:novel_app/models/novel.dart' as _i4;
import 'package:novel_app/models/search_result.dart' as _i14;
import 'package:novel_app/services/api_service_wrapper.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDefaultApi_0 extends _i1.SmartFake implements _i2.DefaultApi {
  _FakeDefaultApi_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNovel_2 extends _i1.SmartFake implements _i4.Novel {
  _FakeNovel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChapterContentResult_3 extends _i1.SmartFake
    implements _i5.ChapterContentResult {
  _FakeChapterContentResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageToVideoResponse_4 extends _i1.SmartFake
    implements _i2.ImageToVideoResponse {
  _FakeImageToVideoResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoStatusResponse_5 extends _i1.SmartFake
    implements _i2.VideoStatusResponse {
  _FakeVideoStatusResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModelsResponse_6 extends _i1.SmartFake
    implements _i2.ModelsResponse {
  _FakeModelsResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBackupUploadResponse_7 extends _i1.SmartFake
    implements _i2.BackupUploadResponse {
  _FakeBackupUploadResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAiAccompanimentSettings_8 extends _i1.SmartFake
    implements _i6.AiAccompanimentSettings {
  _FakeAiAccompanimentSettings_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiServiceWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServiceWrapper extends _i1.Mock implements _i7.ApiServiceWrapper {
  MockApiServiceWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DefaultApi get defaultApi => (super.noSuchMethod(
        Invocation.getter(#defaultApi),
        returnValue: _FakeDefaultApi_0(
          this,
          Invocation.getter(#defaultApi),
        ),
      ) as _i2.DefaultApi);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_1(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i3.Dio);

  @override
  _i8.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  Map<String, dynamic> getInitStatus() => (super.noSuchMethod(
        Invocation.method(
          #getInitStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i8.Future<String?> getHost() => (super.noSuchMethod(
        Invocation.method(
          #getHost,
          [],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<void> setConfig({
    required String? host,
    String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setConfig,
          [],
          {
            #host: host,
            #token: token,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.Novel>> searchNovels(
    String? keyword, {
    List<String>? sites,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchNovels,
          [keyword],
          {#sites: sites},
        ),
        returnValue: _i8.Future<List<_i4.Novel>>.value(<_i4.Novel>[]),
      ) as _i8.Future<List<_i4.Novel>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getSourceSites() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSourceSites,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<_i9.Chapter>> getChapters(
    String? novelUrl, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapters,
          [novelUrl],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i8.Future<List<_i9.Chapter>>.value(<_i9.Chapter>[]),
      ) as _i8.Future<List<_i9.Chapter>>);

  @override
  _i8.Future<(_i4.Novel, List<_i9.Chapter>)> getNovelByUrl(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNovelByUrl,
          [url],
        ),
        returnValue: _i8.Future<(_i4.Novel, List<_i9.Chapter>)>.value((
          _FakeNovel_2(
            this,
            Invocation.method(
              #getNovelByUrl,
              [url],
            ),
          ),
          <_i9.Chapter>[]
        )),
      ) as _i8.Future<(_i4.Novel, List<_i9.Chapter>)>);

  @override
  _i8.Future<String> getChapterContent(
    String? chapterUrl, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapterContent,
          [chapterUrl],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i8.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getChapterContent,
            [chapterUrl],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<_i5.ChapterContentResult> getChapterContentWithSource(
    String? chapterUrl, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapterContentWithSource,
          [chapterUrl],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i8.Future<_i5.ChapterContentResult>.value(
            _FakeChapterContentResult_3(
          this,
          Invocation.method(
            #getChapterContentWithSource,
            [chapterUrl],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i8.Future<_i5.ChapterContentResult>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<Map<String, dynamic>> generateRoleCardImages({
    required String? roleId,
    required Map<String, dynamic>? roles,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateRoleCardImages,
          [],
          {
            #roleId: roleId,
            #roles: roles,
            #modelName: modelName,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getRoleGallery(String? roleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoleGallery,
          [roleId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<bool> deleteRoleImage({
    required String? roleId,
    required String? imageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRoleImage,
          [],
          {
            #roleId: roleId,
            #imageUrl: imageUrl,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<Map<String, dynamic>> generateMoreImages({
    required String? roleId,
    required int? count,
    String? referenceImageUrl,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateMoreImages,
          [],
          {
            #roleId: roleId,
            #count: count,
            #referenceImageUrl: referenceImageUrl,
            #modelName: modelName,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> createSceneIllustration({
    required String? chaptersContent,
    required String? taskId,
    required dynamic roles,
    required int? num,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSceneIllustration,
          [],
          {
            #chaptersContent: chaptersContent,
            #taskId: taskId,
            #roles: roles,
            #num: num,
            #modelName: modelName,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getSceneIllustrationGallery(
          String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationGallery,
          [taskId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> deleteSceneIllustrationImage({
    required String? taskId,
    required String? filename,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSceneIllustrationImage,
          [],
          {
            #taskId: taskId,
            #filename: filename,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> regenerateSceneIllustration({
    required String? taskId,
    required int? count,
    String? model,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #regenerateSceneIllustration,
          [],
          {
            #taskId: taskId,
            #count: count,
            #model: model,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i11.Uint8List> getImageProxy(String? filename) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImageProxy,
          [filename],
        ),
        returnValue: _i8.Future<_i11.Uint8List>.value(_i11.Uint8List(0)),
      ) as _i8.Future<_i11.Uint8List>);

  @override
  _i8.Future<_i2.ImageToVideoResponse> generateVideoFromImage({
    required String? imgName,
    required String? userInput,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateVideoFromImage,
          [],
          {
            #imgName: imgName,
            #userInput: userInput,
            #modelName: modelName,
          },
        ),
        returnValue: _i8.Future<_i2.ImageToVideoResponse>.value(
            _FakeImageToVideoResponse_4(
          this,
          Invocation.method(
            #generateVideoFromImage,
            [],
            {
              #imgName: imgName,
              #userInput: userInput,
              #modelName: modelName,
            },
          ),
        )),
      ) as _i8.Future<_i2.ImageToVideoResponse>);

  @override
  _i8.Future<_i2.VideoStatusResponse> checkVideoStatus(String? imgName) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkVideoStatus,
          [imgName],
        ),
        returnValue: _i8.Future<_i2.VideoStatusResponse>.value(
            _FakeVideoStatusResponse_5(
          this,
          Invocation.method(
            #checkVideoStatus,
            [imgName],
          ),
        )),
      ) as _i8.Future<_i2.VideoStatusResponse>);

  @override
  _i8.Future<String> getVideoFileUrl(String? imgName) => (super.noSuchMethod(
        Invocation.method(
          #getVideoFileUrl,
          [imgName],
        ),
        returnValue: _i8.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getVideoFileUrl,
            [imgName],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<Map<String, dynamic>> regenerateSceneIllustrationImages({
    required String? taskId,
    required int? count,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #regenerateSceneIllustrationImages,
          [],
          {
            #taskId: taskId,
            #count: count,
            #modelName: modelName,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i2.ModelsResponse> getModels() => (super.noSuchMethod(
        Invocation.method(
          #getModels,
          [],
        ),
        returnValue: _i8.Future<_i2.ModelsResponse>.value(_FakeModelsResponse_6(
          this,
          Invocation.method(
            #getModels,
            [],
          ),
        )),
      ) as _i8.Future<_i2.ModelsResponse>);

  @override
  _i8.Future<List<String>> getModelTitles({String? apiType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModelTitles,
          [],
          {#apiType: apiType},
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<_i2.BackupUploadResponse> uploadBackup({
    required _i12.File? dbFile,
    _i3.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBackup,
          [],
          {
            #dbFile: dbFile,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i8.Future<_i2.BackupUploadResponse>.value(
            _FakeBackupUploadResponse_7(
          this,
          Invocation.method(
            #uploadBackup,
            [],
            {
              #dbFile: dbFile,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i8.Future<_i2.BackupUploadResponse>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getBackupList() => (super.noSuchMethod(
        Invocation.method(
          #getBackupList,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<String> downloadBackup({
    required String? backupId,
    required String? savePath,
    _i3.ProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadBackup,
          [],
          {
            #backupId: backupId,
            #savePath: savePath,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i8.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #downloadBackup,
            [],
            {
              #backupId: backupId,
              #savePath: savePath,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<void> deleteBackupOnServer({required String? backupId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBackupOnServer,
          [],
          {#backupId: backupId},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [IChapterRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChapterRepository extends _i1.Mock
    implements _i13.IChapterRepository {
  MockIChapterRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> isChapterCached(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isChapterCached,
          [chapterUrl],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<List<String>> filterUncachedChapters(List<String>? chapterUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterUncachedChapters,
          [chapterUrls],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<Map<String, bool>> getChaptersCacheStatus(
          List<String>? chapterUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChaptersCacheStatus,
          [chapterUrls],
        ),
        returnValue: _i8.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i8.Future<Map<String, bool>>);

  @override
  void markAsPreloading(String? chapterUrl) => super.noSuchMethod(
        Invocation.method(
          #markAsPreloading,
          [chapterUrl],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isPreloading(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isPreloading,
          [chapterUrl],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearMemoryState() => super.noSuchMethod(
        Invocation.method(
          #clearMemoryState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<int> cacheChapter(
    String? novelUrl,
    _i9.Chapter? chapter,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheChapter,
          [
            novelUrl,
            chapter,
            content,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> updateChapterContent(
    String? chapterUrl,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChapterContent,
          [
            chapterUrl,
            content,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> deleteChapterCache(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteChapterCache,
          [chapterUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<String?> getCachedChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapter,
          [chapterUrl],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<List<_i9.Chapter>> getCachedChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapters,
          [novelUrl],
        ),
        returnValue: _i8.Future<List<_i9.Chapter>>.value(<_i9.Chapter>[]),
      ) as _i8.Future<List<_i9.Chapter>>);

  @override
  _i8.Future<int> deleteCachedChapters(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteCachedChapters,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<bool> isChapterAccompanied(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isChapterAccompanied,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> markChapterAsAccompanied(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markChapterAsAccompanied,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> resetChapterAccompaniedFlag(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetChapterAccompaniedFlag,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cacheNovelChapters(
    String? novelUrl,
    List<_i9.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheNovelChapters,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i9.Chapter>> getCachedNovelChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNovelChapters,
          [novelUrl],
        ),
        returnValue: _i8.Future<List<_i9.Chapter>>.value(<_i9.Chapter>[]),
      ) as _i8.Future<List<_i9.Chapter>>);

  @override
  _i8.Future<int> createCustomChapter(
    String? novelUrl,
    String? title,
    String? content, [
    int? index,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomChapter,
          [
            novelUrl,
            title,
            content,
            index,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> updateCustomChapter(
    String? chapterUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomChapter,
          [
            chapterUrl,
            title,
            content,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteCustomChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomChapter,
          [chapterUrl],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> markChapterAsRead(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markChapterAsRead,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<int> getCachedChaptersCount(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChaptersCount,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> getTotalChaptersCount(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalChaptersCount,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> updateChaptersOrder(
    String? novelUrl,
    List<_i9.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChaptersOrder,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i14.ChapterSearchResult>> searchInCachedContent(
    String? keyword, {
    String? novelUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchInCachedContent,
          [keyword],
          {#novelUrl: novelUrl},
        ),
        returnValue: _i8.Future<List<_i14.ChapterSearchResult>>.value(
            <_i14.ChapterSearchResult>[]),
      ) as _i8.Future<List<_i14.ChapterSearchResult>>);

  @override
  _i8.Future<_i9.Chapter?> getChapterById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getChapterById,
          [id],
        ),
        returnValue: _i8.Future<_i9.Chapter?>.value(),
      ) as _i8.Future<_i9.Chapter?>);

  @override
  _i8.Future<String?> getChapterUrlById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getChapterUrlById,
          [id],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<bool> chapterExistsById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #chapterExistsById,
          [id],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<int> updateChapterContentById(
    int? id,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChapterContentById,
          [
            id,
            content,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int?> getChapterIdByUrl(String? url) => (super.noSuchMethod(
        Invocation.method(
          #getChapterIdByUrl,
          [url],
        ),
        returnValue: _i8.Future<int?>.value(),
      ) as _i8.Future<int?>);
}

/// A class which mocks [INovelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockINovelRepository extends _i1.Mock implements _i15.INovelRepository {
  MockINovelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<int> addToBookshelf(_i4.Novel? novel) => (super.noSuchMethod(
        Invocation.method(
          #addToBookshelf,
          [novel],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> removeFromBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeFromBookshelf,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<_i4.Novel>> getNovels() => (super.noSuchMethod(
        Invocation.method(
          #getNovels,
          [],
        ),
        returnValue: _i8.Future<List<_i4.Novel>>.value(<_i4.Novel>[]),
      ) as _i8.Future<List<_i4.Novel>>);

  @override
  _i8.Future<bool> isInBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #isInBookshelf,
          [novelUrl],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<int> updateLastReadChapter(
    String? novelUrl,
    int? chapterIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastReadChapter,
          [
            novelUrl,
            chapterIndex,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> updateTitle(
    String? novelUrl,
    String? newTitle,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTitle,
          [
            novelUrl,
            newTitle,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> updateBackgroundSetting(
    String? novelUrl,
    String? backgroundSetting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSetting,
          [
            novelUrl,
            backgroundSetting,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<String?> getBackgroundSetting(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackgroundSetting,
          [novelUrl],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<int> getLastReadChapter(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #getLastReadChapter,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<_i6.AiAccompanimentSettings> getAiAccompanimentSettings(
          String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAiAccompanimentSettings,
          [novelUrl],
        ),
        returnValue: _i8.Future<_i6.AiAccompanimentSettings>.value(
            _FakeAiAccompanimentSettings_8(
          this,
          Invocation.method(
            #getAiAccompanimentSettings,
            [novelUrl],
          ),
        )),
      ) as _i8.Future<_i6.AiAccompanimentSettings>);

  @override
  _i8.Future<int> updateAiAccompanimentSettings(
    String? novelUrl,
    _i6.AiAccompanimentSettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAiAccompanimentSettings,
          [
            novelUrl,
            settings,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<_i4.Novel?> getNovelByTitle(String? title) => (super.noSuchMethod(
        Invocation.method(
          #getNovelByTitle,
          [title],
        ),
        returnValue: _i8.Future<_i4.Novel?>.value(),
      ) as _i8.Future<_i4.Novel?>);

  @override
  _i8.Future<_i4.Novel> createNovel({
    required String? title,
    required String? author,
    String? description,
    String? coverUrl,
    String? backgroundSetting,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNovel,
          [],
          {
            #title: title,
            #author: author,
            #description: description,
            #coverUrl: coverUrl,
            #backgroundSetting: backgroundSetting,
          },
        ),
        returnValue: _i8.Future<_i4.Novel>.value(_FakeNovel_2(
          this,
          Invocation.method(
            #createNovel,
            [],
            {
              #title: title,
              #author: author,
              #description: description,
              #coverUrl: coverUrl,
              #backgroundSetting: backgroundSetting,
            },
          ),
        )),
      ) as _i8.Future<_i4.Novel>);

  @override
  _i8.Future<_i4.Novel?> getNovelById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getNovelById,
          [id],
        ),
        returnValue: _i8.Future<_i4.Novel?>.value(),
      ) as _i8.Future<_i4.Novel?>);

  @override
  _i8.Future<String?> getNovelUrlById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getNovelUrlById,
          [id],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<int> updateBackgroundSettingById(
    int? id,
    String? setting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSettingById,
          [
            id,
            setting,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);
}
