// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/test_helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i20;

import 'package:dio/dio.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:novel_api/novel_api.dart' as _i5;
import 'package:novel_app/models/ai_accompaniment_settings.dart' as _i3;
import 'package:novel_app/models/ai_companion_response.dart' as _i17;
import 'package:novel_app/models/bookshelf.dart' as _i18;
import 'package:novel_app/models/chapter.dart' as _i10;
import 'package:novel_app/models/character.dart' as _i4;
import 'package:novel_app/models/character_relationship.dart' as _i13;
import 'package:novel_app/models/chat_scene.dart' as _i16;
import 'package:novel_app/models/novel.dart' as _i9;
import 'package:novel_app/models/outline.dart' as _i15;
import 'package:novel_app/models/scene_illustration.dart' as _i14;
import 'package:novel_app/models/search_result.dart' as _i11;
import 'package:novel_app/services/api_service_wrapper.dart' as _i19;
import 'package:novel_app/services/database_service.dart' as _i7;
import 'package:novel_app/services/dify_service.dart' as _i21;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAiAccompanimentSettings_1 extends _i1.SmartFake
    implements _i3.AiAccompanimentSettings {
  _FakeAiAccompanimentSettings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCharacter_2 extends _i1.SmartFake implements _i4.Character {
  _FakeCharacter_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDefaultApi_3 extends _i1.SmartFake implements _i5.DefaultApi {
  _FakeDefaultApi_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_4 extends _i1.SmartFake implements _i6.Dio {
  _FakeDio_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageToVideoResponse_5 extends _i1.SmartFake
    implements _i5.ImageToVideoResponse {
  _FakeImageToVideoResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoStatusResponse_6 extends _i1.SmartFake
    implements _i5.VideoStatusResponse {
  _FakeVideoStatusResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModelsResponse_7 extends _i1.SmartFake
    implements _i5.ModelsResponse {
  _FakeModelsResponse_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i7.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isWebPlatform => (super.noSuchMethod(
        Invocation.getter(#isWebPlatform),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i8.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i8.Future<_i2.Database>);

  @override
  _i8.Future<int> addToBookshelf(_i9.Novel? novel) => (super.noSuchMethod(
        Invocation.method(
          #addToBookshelf,
          [novel],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> removeFromBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeFromBookshelf,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<_i9.Novel>> getBookshelf() => (super.noSuchMethod(
        Invocation.method(
          #getBookshelf,
          [],
        ),
        returnValue: _i8.Future<List<_i9.Novel>>.value(<_i9.Novel>[]),
      ) as _i8.Future<List<_i9.Novel>>);

  @override
  _i8.Future<bool> isInBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #isInBookshelf,
          [novelUrl],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<int> updateLastReadChapter(
    String? novelUrl,
    int? chapterIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastReadChapter,
          [
            novelUrl,
            chapterIndex,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> updateBackgroundSetting(
    String? novelUrl,
    String? backgroundSetting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSetting,
          [
            novelUrl,
            backgroundSetting,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<_i3.AiAccompanimentSettings> getAiAccompanimentSettings(
          String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAiAccompanimentSettings,
          [novelUrl],
        ),
        returnValue: _i8.Future<_i3.AiAccompanimentSettings>.value(
            _FakeAiAccompanimentSettings_1(
          this,
          Invocation.method(
            #getAiAccompanimentSettings,
            [novelUrl],
          ),
        )),
      ) as _i8.Future<_i3.AiAccompanimentSettings>);

  @override
  _i8.Future<int> updateAiAccompanimentSettings(
    String? novelUrl,
    _i3.AiAccompanimentSettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAiAccompanimentSettings,
          [
            novelUrl,
            settings,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<String?> getBackgroundSetting(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackgroundSetting,
          [novelUrl],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<int> getLastReadChapter(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #getLastReadChapter,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<bool> isChapterCached(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isChapterCached,
          [chapterUrl],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<List<String>> filterUncachedChapters(List<String>? chapterUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterUncachedChapters,
          [chapterUrls],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  void markAsPreloading(String? chapterUrl) => super.noSuchMethod(
        Invocation.method(
          #markAsPreloading,
          [chapterUrl],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isPreloading(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isPreloading,
          [chapterUrl],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearMemoryState() => super.noSuchMethod(
        Invocation.method(
          #clearMemoryState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<int> cacheChapter(
    String? novelUrl,
    _i10.Chapter? chapter,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheChapter,
          [
            novelUrl,
            chapter,
            content,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> updateChapterContent(
    String? chapterUrl,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChapterContent,
          [
            chapterUrl,
            content,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> deleteChapterCache(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteChapterCache,
          [chapterUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<String?> getCachedChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapter,
          [chapterUrl],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<List<_i10.Chapter>> getCachedChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapters,
          [novelUrl],
        ),
        returnValue: _i8.Future<List<_i10.Chapter>>.value(<_i10.Chapter>[]),
      ) as _i8.Future<List<_i10.Chapter>>);

  @override
  _i8.Future<int> deleteCachedChapters(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteCachedChapters,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<bool> isChapterAccompanied(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isChapterAccompanied,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> markChapterAsAccompanied(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markChapterAsAccompanied,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> resetChapterAccompaniedFlag(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetChapterAccompaniedFlag,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearNovelCache(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #clearNovelCache,
          [novelUrl],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, int>> getNovelCacheStats(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNovelCacheStats,
          [novelUrl],
        ),
        returnValue: _i8.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i8.Future<Map<String, int>>);

  @override
  _i8.Future<void> cacheWholeNovel(
    String? novelUrl,
    List<_i10.Chapter>? chapters,
    _i8.Future<String> Function(String)? getContent,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWholeNovel,
          [
            novelUrl,
            chapters,
            getContent,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> cacheNovelChapters(
    String? novelUrl,
    List<_i10.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheNovelChapters,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i10.Chapter>> getCachedNovelChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNovelChapters,
          [novelUrl],
        ),
        returnValue: _i8.Future<List<_i10.Chapter>>.value(<_i10.Chapter>[]),
      ) as _i8.Future<List<_i10.Chapter>>);

  @override
  _i8.Future<void> insertUserChapter(
    String? novelUrl,
    String? title,
    String? content,
    int? insertIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertUserChapter,
          [
            novelUrl,
            title,
            content,
            insertIndex,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<int> createCustomNovel(
    String? title,
    String? author, {
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomNovel,
          [
            title,
            author,
          ],
          {#description: description},
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> createCustomChapter(
    String? novelUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomChapter,
          [
            novelUrl,
            title,
            content,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> updateChaptersOrder(
    String? novelUrl,
    List<_i10.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChaptersOrder,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String?> getCustomChapterContent(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomChapterContent,
          [chapterUrl],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<void> updateCustomChapter(
    String? chapterUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomChapter,
          [
            chapterUrl,
            title,
            content,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteCustomChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomChapter,
          [chapterUrl],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i11.ChapterSearchResult>> searchInCachedContent(
    String? keyword, {
    String? novelUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchInCachedContent,
          [keyword],
          {#novelUrl: novelUrl},
        ),
        returnValue: _i8.Future<List<_i11.ChapterSearchResult>>.value(
            <_i11.ChapterSearchResult>[]),
      ) as _i8.Future<List<_i11.ChapterSearchResult>>);

  @override
  _i8.Future<List<_i11.CachedNovelInfo>> getCachedNovels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNovels,
          [],
        ),
        returnValue: _i8.Future<List<_i11.CachedNovelInfo>>.value(
            <_i11.CachedNovelInfo>[]),
      ) as _i8.Future<List<_i11.CachedNovelInfo>>);

  @override
  _i8.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateNovelInBookshelf(_i9.Novel? novel) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNovelInBookshelf,
          [novel],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearBookshelfCache() => (super.noSuchMethod(
        Invocation.method(
          #clearBookshelfCache,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<int> getCachedChaptersCount(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChaptersCount,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<_i10.Chapter?> getChapterByUrl(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapterByUrl,
          [chapterUrl],
        ),
        returnValue: _i8.Future<_i10.Chapter?>.value(),
      ) as _i8.Future<_i10.Chapter?>);

  @override
  _i8.Future<void> deleteUserChapter(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteUserChapter,
          [chapterUrl],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateReadingProgress(
    String? novelUrl,
    int? chapterIndex,
    double? progress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReadingProgress,
          [
            novelUrl,
            chapterIndex,
            progress,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<int> createCharacter(_i4.Character? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCharacter,
          [character],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<_i4.Character>> getCharacters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacters,
          [novelUrl],
        ),
        returnValue: _i8.Future<List<_i4.Character>>.value(<_i4.Character>[]),
      ) as _i8.Future<List<_i4.Character>>);

  @override
  _i8.Future<_i4.Character?> getCharacter(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getCharacter,
          [id],
        ),
        returnValue: _i8.Future<_i4.Character?>.value(),
      ) as _i8.Future<_i4.Character?>);

  @override
  _i8.Future<int> updateCharacter(_i4.Character? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacter,
          [character],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> deleteCharacter(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCharacter,
          [id],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<_i4.Character?> findCharacterByName(
    String? novelUrl,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCharacterByName,
          [
            novelUrl,
            name,
          ],
        ),
        returnValue: _i8.Future<_i4.Character?>.value(),
      ) as _i8.Future<_i4.Character?>);

  @override
  _i8.Future<_i4.Character> updateOrInsertCharacter(
          _i4.Character? newCharacter) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrInsertCharacter,
          [newCharacter],
        ),
        returnValue: _i8.Future<_i4.Character>.value(_FakeCharacter_2(
          this,
          Invocation.method(
            #updateOrInsertCharacter,
            [newCharacter],
          ),
        )),
      ) as _i8.Future<_i4.Character>);

  @override
  _i8.Future<List<_i4.Character>> batchUpdateCharacters(
          List<_i4.Character>? newCharacters) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateCharacters,
          [newCharacters],
        ),
        returnValue: _i8.Future<List<_i4.Character>>.value(<_i4.Character>[]),
      ) as _i8.Future<List<_i4.Character>>);

  @override
  _i8.Future<List<String>> getCharacterNames(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterNames,
          [novelUrl],
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);

  @override
  _i8.Future<bool> characterExists(int? id) => (super.noSuchMethod(
        Invocation.method(
          #characterExists,
          [id],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<List<_i4.Character>> getCharactersByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharactersByIds,
          [ids],
        ),
        returnValue: _i8.Future<List<_i4.Character>>.value(<_i4.Character>[]),
      ) as _i8.Future<List<_i4.Character>>);

  @override
  _i8.Future<int> deleteAllCharacters(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllCharacters,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> updateCharacterCachedImage(
    int? characterId,
    String? imageUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterCachedImage,
          [
            characterId,
            imageUrl,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> clearCharacterCachedImage(int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCharacterCachedImage,
          [characterId],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> clearAllCharacterCachedImages(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearAllCharacterCachedImages,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<_i10.Chapter>> getChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapters,
          [novelUrl],
        ),
        returnValue: _i8.Future<List<_i10.Chapter>>.value(<_i10.Chapter>[]),
      ) as _i8.Future<List<_i10.Chapter>>);

  @override
  _i8.Future<void> markChapterAsRead(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markChapterAsRead,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String> getChapterContent(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapterContent,
          [chapterUrl],
        ),
        returnValue: _i8.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getChapterContent,
            [chapterUrl],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String> getCachedChapterContent(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapterContent,
          [chapterUrl],
        ),
        returnValue: _i8.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getCachedChapterContent,
            [chapterUrl],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<String?> getCharacterCachedImage(int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterCachedImage,
          [characterId],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<int> updateCharacterAvatar(
    int? characterId, {
    String? imageUrl,
    String? originalFilename,
    String? originalImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterAvatar,
          [characterId],
          {
            #imageUrl: imageUrl,
            #originalFilename: originalFilename,
            #originalImageUrl: originalImageUrl,
          },
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<bool> hasCharacterAvatar(int? characterId) => (super.noSuchMethod(
        Invocation.method(
          #hasCharacterAvatar,
          [characterId],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<int> createRelationship(
          _i13.CharacterRelationship? relationship) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRelationship,
          [relationship],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<_i13.CharacterRelationship>> getRelationships(
          int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelationships,
          [characterId],
        ),
        returnValue: _i8.Future<List<_i13.CharacterRelationship>>.value(
            <_i13.CharacterRelationship>[]),
      ) as _i8.Future<List<_i13.CharacterRelationship>>);

  @override
  _i8.Future<List<_i13.CharacterRelationship>> getOutgoingRelationships(
          int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOutgoingRelationships,
          [characterId],
        ),
        returnValue: _i8.Future<List<_i13.CharacterRelationship>>.value(
            <_i13.CharacterRelationship>[]),
      ) as _i8.Future<List<_i13.CharacterRelationship>>);

  @override
  _i8.Future<List<_i13.CharacterRelationship>> getIncomingRelationships(
          int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIncomingRelationships,
          [characterId],
        ),
        returnValue: _i8.Future<List<_i13.CharacterRelationship>>.value(
            <_i13.CharacterRelationship>[]),
      ) as _i8.Future<List<_i13.CharacterRelationship>>);

  @override
  _i8.Future<int> updateRelationship(
          _i13.CharacterRelationship? relationship) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRelationship,
          [relationship],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> deleteRelationship(int? relationshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRelationship,
          [relationshipId],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<bool> relationshipExists(
    int? sourceId,
    int? targetId,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #relationshipExists,
          [
            sourceId,
            targetId,
            type,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<int> getRelationshipCount(int? characterId) => (super.noSuchMethod(
        Invocation.method(
          #getRelationshipCount,
          [characterId],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<int>> getRelatedCharacterIds(int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelatedCharacterIds,
          [characterId],
        ),
        returnValue: _i8.Future<List<int>>.value(<int>[]),
      ) as _i8.Future<List<int>>);

  @override
  _i8.Future<int> insertSceneIllustration(
          _i14.SceneIllustration? illustration) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSceneIllustration,
          [illustration],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> updateSceneIllustrationStatus(
    int? id,
    String? status, {
    List<String>? images,
    String? prompts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSceneIllustrationStatus,
          [
            id,
            status,
          ],
          {
            #images: images,
            #prompts: prompts,
          },
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<_i14.SceneIllustration>> getSceneIllustrationsByChapter(
    String? novelUrl,
    String? chapterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationsByChapter,
          [
            novelUrl,
            chapterId,
          ],
        ),
        returnValue: _i8.Future<List<_i14.SceneIllustration>>.value(
            <_i14.SceneIllustration>[]),
      ) as _i8.Future<List<_i14.SceneIllustration>>);

  @override
  _i8.Future<_i14.SceneIllustration?> getSceneIllustrationByTaskId(
          String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationByTaskId,
          [taskId],
        ),
        returnValue: _i8.Future<_i14.SceneIllustration?>.value(),
      ) as _i8.Future<_i14.SceneIllustration?>);

  @override
  _i8.Future<Map<String, dynamic>> getSceneIllustrationsPaginated({
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationsPaginated,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<int> deleteSceneIllustration(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSceneIllustration,
          [id],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> deleteSceneIllustrationsByChapter(
    String? novelUrl,
    String? chapterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSceneIllustrationsByChapter,
          [
            novelUrl,
            chapterId,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<_i14.SceneIllustration>> getPendingSceneIllustrations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSceneIllustrations,
          [],
        ),
        returnValue: _i8.Future<List<_i14.SceneIllustration>>.value(
            <_i14.SceneIllustration>[]),
      ) as _i8.Future<List<_i14.SceneIllustration>>);

  @override
  _i8.Future<int> batchUpdateSceneIllustrations(
    List<int>? ids,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateSceneIllustrations,
          [
            ids,
            status,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> saveOutline(_i15.Outline? outline) => (super.noSuchMethod(
        Invocation.method(
          #saveOutline,
          [outline],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<_i15.Outline?> getOutlineByNovelUrl(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOutlineByNovelUrl,
          [novelUrl],
        ),
        returnValue: _i8.Future<_i15.Outline?>.value(),
      ) as _i8.Future<_i15.Outline?>);

  @override
  _i8.Future<List<_i15.Outline>> getAllOutlines() => (super.noSuchMethod(
        Invocation.method(
          #getAllOutlines,
          [],
        ),
        returnValue: _i8.Future<List<_i15.Outline>>.value(<_i15.Outline>[]),
      ) as _i8.Future<List<_i15.Outline>>);

  @override
  _i8.Future<int> deleteOutline(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteOutline,
          [novelUrl],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> updateOutlineContent(
    String? novelUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOutlineContent,
          [
            novelUrl,
            title,
            content,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> insertChatScene(_i16.ChatScene? scene) => (super.noSuchMethod(
        Invocation.method(
          #insertChatScene,
          [scene],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<void> updateChatScene(_i16.ChatScene? scene) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatScene,
          [scene],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteChatScene(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteChatScene,
          [id],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i16.ChatScene>> getAllChatScenes() => (super.noSuchMethod(
        Invocation.method(
          #getAllChatScenes,
          [],
        ),
        returnValue: _i8.Future<List<_i16.ChatScene>>.value(<_i16.ChatScene>[]),
      ) as _i8.Future<List<_i16.ChatScene>>);

  @override
  _i8.Future<_i16.ChatScene?> getChatSceneById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getChatSceneById,
          [id],
        ),
        returnValue: _i8.Future<_i16.ChatScene?>.value(),
      ) as _i8.Future<_i16.ChatScene?>);

  @override
  _i8.Future<List<_i16.ChatScene>> searchChatScenes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchChatScenes,
          [query],
        ),
        returnValue: _i8.Future<List<_i16.ChatScene>>.value(<_i16.ChatScene>[]),
      ) as _i8.Future<List<_i16.ChatScene>>);

  @override
  _i8.Future<int> appendBackgroundSetting(
    String? novelUrl,
    String? newBackground,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #appendBackgroundSetting,
          [
            novelUrl,
            newBackground,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> batchUpdateOrInsertCharacters(
    String? novelUrl,
    List<_i17.AICompanionRole>? aiRoles,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateOrInsertCharacters,
          [
            novelUrl,
            aiRoles,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<int> batchUpdateOrInsertRelationships(
    String? novelUrl,
    List<_i17.AICompanionRelation>? aiRelations,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateOrInsertRelationships,
          [
            novelUrl,
            aiRelations,
          ],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<List<_i13.CharacterRelationship>> getAllRelationships(
          String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllRelationships,
          [novelUrl],
        ),
        returnValue: _i8.Future<List<_i13.CharacterRelationship>>.value(
            <_i13.CharacterRelationship>[]),
      ) as _i8.Future<List<_i13.CharacterRelationship>>);

  @override
  _i8.Future<List<_i18.Bookshelf>> getBookshelves() => (super.noSuchMethod(
        Invocation.method(
          #getBookshelves,
          [],
        ),
        returnValue: _i8.Future<List<_i18.Bookshelf>>.value(<_i18.Bookshelf>[]),
      ) as _i8.Future<List<_i18.Bookshelf>>);

  @override
  _i8.Future<int> createBookshelf(String? name) => (super.noSuchMethod(
        Invocation.method(
          #createBookshelf,
          [name],
        ),
        returnValue: _i8.Future<int>.value(0),
      ) as _i8.Future<int>);

  @override
  _i8.Future<bool> deleteBookshelf(int? bookshelfId) => (super.noSuchMethod(
        Invocation.method(
          #deleteBookshelf,
          [bookshelfId],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<List<_i9.Novel>> getNovelsByBookshelf(int? bookshelfId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNovelsByBookshelf,
          [bookshelfId],
        ),
        returnValue: _i8.Future<List<_i9.Novel>>.value(<_i9.Novel>[]),
      ) as _i8.Future<List<_i9.Novel>>);

  @override
  _i8.Future<void> addNovelToBookshelf(
    String? novelUrl,
    int? bookshelfId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNovelToBookshelf,
          [
            novelUrl,
            bookshelfId,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> removeNovelFromBookshelf(
    String? novelUrl,
    int? bookshelfId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeNovelFromBookshelf,
          [
            novelUrl,
            bookshelfId,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<List<int>> getBookshelvesByNovel(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookshelvesByNovel,
          [novelUrl],
        ),
        returnValue: _i8.Future<List<int>>.value(<int>[]),
      ) as _i8.Future<List<int>>);
}

/// A class which mocks [ApiServiceWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServiceWrapper extends _i1.Mock implements _i19.ApiServiceWrapper {
  MockApiServiceWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.DefaultApi get defaultApi => (super.noSuchMethod(
        Invocation.getter(#defaultApi),
        returnValue: _FakeDefaultApi_3(
          this,
          Invocation.getter(#defaultApi),
        ),
      ) as _i5.DefaultApi);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i6.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_4(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i6.Dio);

  @override
  _i8.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  Map<String, dynamic> getInitStatus() => (super.noSuchMethod(
        Invocation.method(
          #getInitStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i8.Future<String?> getHost() => (super.noSuchMethod(
        Invocation.method(
          #getHost,
          [],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<void> setConfig({
    required String? host,
    String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setConfig,
          [],
          {
            #host: host,
            #token: token,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i9.Novel>> searchNovels(
    String? keyword, {
    List<String>? sites,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchNovels,
          [keyword],
          {#sites: sites},
        ),
        returnValue: _i8.Future<List<_i9.Novel>>.value(<_i9.Novel>[]),
      ) as _i8.Future<List<_i9.Novel>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getSourceSites() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSourceSites,
          [],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<_i10.Chapter>> getChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapters,
          [novelUrl],
        ),
        returnValue: _i8.Future<List<_i10.Chapter>>.value(<_i10.Chapter>[]),
      ) as _i8.Future<List<_i10.Chapter>>);

  @override
  _i8.Future<String> getChapterContent(
    String? chapterUrl, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapterContent,
          [chapterUrl],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i8.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getChapterContent,
            [chapterUrl],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i8.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<Map<String, dynamic>> generateRoleCardImages({
    required String? roleId,
    required Map<String, dynamic>? roles,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateRoleCardImages,
          [],
          {
            #roleId: roleId,
            #roles: roles,
            #modelName: modelName,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getRoleGallery(String? roleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoleGallery,
          [roleId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<bool> deleteRoleImage({
    required String? roleId,
    required String? imageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRoleImage,
          [],
          {
            #roleId: roleId,
            #imageUrl: imageUrl,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<Map<String, dynamic>> generateMoreImages({
    required String? roleId,
    required int? count,
    String? referenceImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateMoreImages,
          [],
          {
            #roleId: roleId,
            #count: count,
            #referenceImageUrl: referenceImageUrl,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> createSceneIllustration({
    required String? chaptersContent,
    required String? taskId,
    required dynamic roles,
    required int? num,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSceneIllustration,
          [],
          {
            #chaptersContent: chaptersContent,
            #taskId: taskId,
            #roles: roles,
            #num: num,
            #modelName: modelName,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getSceneIllustrationGallery(
          String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationGallery,
          [taskId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> deleteSceneIllustrationImage({
    required String? taskId,
    required String? filename,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSceneIllustrationImage,
          [],
          {
            #taskId: taskId,
            #filename: filename,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> regenerateSceneIllustration({
    required String? taskId,
    required int? count,
    String? model,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #regenerateSceneIllustration,
          [],
          {
            #taskId: taskId,
            #count: count,
            #model: model,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i20.Uint8List> getImageProxy(String? filename) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImageProxy,
          [filename],
        ),
        returnValue: _i8.Future<_i20.Uint8List>.value(_i20.Uint8List(0)),
      ) as _i8.Future<_i20.Uint8List>);

  @override
  _i8.Future<_i5.ImageToVideoResponse> generateVideoFromImage({
    required String? imgName,
    required String? userInput,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateVideoFromImage,
          [],
          {
            #imgName: imgName,
            #userInput: userInput,
            #modelName: modelName,
          },
        ),
        returnValue: _i8.Future<_i5.ImageToVideoResponse>.value(
            _FakeImageToVideoResponse_5(
          this,
          Invocation.method(
            #generateVideoFromImage,
            [],
            {
              #imgName: imgName,
              #userInput: userInput,
              #modelName: modelName,
            },
          ),
        )),
      ) as _i8.Future<_i5.ImageToVideoResponse>);

  @override
  _i8.Future<_i5.VideoStatusResponse> checkVideoStatus(String? imgName) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkVideoStatus,
          [imgName],
        ),
        returnValue: _i8.Future<_i5.VideoStatusResponse>.value(
            _FakeVideoStatusResponse_6(
          this,
          Invocation.method(
            #checkVideoStatus,
            [imgName],
          ),
        )),
      ) as _i8.Future<_i5.VideoStatusResponse>);

  @override
  _i8.Future<String> getVideoFileUrl(String? imgName) => (super.noSuchMethod(
        Invocation.method(
          #getVideoFileUrl,
          [imgName],
        ),
        returnValue: _i8.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #getVideoFileUrl,
            [imgName],
          ),
        )),
      ) as _i8.Future<String>);

  @override
  _i8.Future<Map<String, dynamic>> regenerateSceneIllustrationImages({
    required String? taskId,
    required int? count,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #regenerateSceneIllustrationImages,
          [],
          {
            #taskId: taskId,
            #count: count,
            #modelName: modelName,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i5.ModelsResponse> getModels() => (super.noSuchMethod(
        Invocation.method(
          #getModels,
          [],
        ),
        returnValue: _i8.Future<_i5.ModelsResponse>.value(_FakeModelsResponse_7(
          this,
          Invocation.method(
            #getModels,
            [],
          ),
        )),
      ) as _i8.Future<_i5.ModelsResponse>);

  @override
  _i8.Future<List<String>> getModelTitles({String? apiType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModelTitles,
          [],
          {#apiType: apiType},
        ),
        returnValue: _i8.Future<List<String>>.value(<String>[]),
      ) as _i8.Future<List<String>>);
}

/// A class which mocks [DifyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDifyService extends _i1.Mock implements _i21.DifyService {
  MockDifyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> generateCloseUpStreaming({
    required String? selectedParagraph,
    required String? userInput,
    required String? currentChapterContent,
    required List<String>? historyChaptersContent,
    String? backgroundSetting = '',
    String? roles,
    required dynamic Function(String)? onChunk,
    dynamic Function()? onComplete,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateCloseUpStreaming,
          [],
          {
            #selectedParagraph: selectedParagraph,
            #userInput: userInput,
            #currentChapterContent: currentChapterContent,
            #historyChaptersContent: historyChaptersContent,
            #backgroundSetting: backgroundSetting,
            #roles: roles,
            #onChunk: onChunk,
            #onComplete: onComplete,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> runWorkflowStreaming({
    required Map<String, dynamic>? inputs,
    required dynamic Function(String)? onData,
    dynamic Function(String)? onError,
    dynamic Function()? onDone,
    bool? enableDebugLog = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWorkflowStreaming,
          [],
          {
            #inputs: inputs,
            #onData: onData,
            #onError: onError,
            #onDone: onDone,
            #enableDebugLog: enableDebugLog,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>?> runWorkflowBlocking(
          {required Map<String, dynamic>? inputs}) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWorkflowBlocking,
          [],
          {#inputs: inputs},
        ),
        returnValue: _i8.Future<Map<String, dynamic>?>.value(),
      ) as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<List<_i4.Character>> generateCharacters({
    required String? userInput,
    required String? novelUrl,
    required String? backgroundSetting,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateCharacters,
          [],
          {
            #userInput: userInput,
            #novelUrl: novelUrl,
            #backgroundSetting: backgroundSetting,
          },
        ),
        returnValue: _i8.Future<List<_i4.Character>>.value(<_i4.Character>[]),
      ) as _i8.Future<List<_i4.Character>>);

  @override
  _i8.Future<List<_i4.Character>> generateCharactersFromOutline({
    required String? outline,
    required String? userInput,
    required String? novelUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateCharactersFromOutline,
          [],
          {
            #outline: outline,
            #userInput: userInput,
            #novelUrl: novelUrl,
          },
        ),
        returnValue: _i8.Future<List<_i4.Character>>.value(<_i4.Character>[]),
      ) as _i8.Future<List<_i4.Character>>);

  @override
  _i8.Future<List<_i4.Character>> updateCharacterCards({
    required String? chaptersContent,
    required String? roles,
    required String? novelUrl,
    String? backgroundSetting = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterCards,
          [],
          {
            #chaptersContent: chaptersContent,
            #roles: roles,
            #novelUrl: novelUrl,
            #backgroundSetting: backgroundSetting,
          },
        ),
        returnValue: _i8.Future<List<_i4.Character>>.value(<_i4.Character>[]),
      ) as _i8.Future<List<_i4.Character>>);

  @override
  _i8.Future<List<_i4.Character>> extractCharacter({
    required String? chapterContent,
    required String? roles,
    required String? novelUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #extractCharacter,
          [],
          {
            #chapterContent: chapterContent,
            #roles: roles,
            #novelUrl: novelUrl,
          },
        ),
        returnValue: _i8.Future<List<_i4.Character>>.value(<_i4.Character>[]),
      ) as _i8.Future<List<_i4.Character>>);

  @override
  _i8.Future<Map<String, String>> generateCharacterPrompts(
          {required String? characterDescription}) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateCharacterPrompts,
          [],
          {#characterDescription: characterDescription},
        ),
        returnValue: _i8.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i8.Future<Map<String, String>>);

  @override
  _i8.Future<void> generateSceneDescriptionStream({
    required String? chapterContent,
    required List<_i4.Character>? characters,
    required dynamic Function(String)? onChunk,
    required dynamic Function(String)? onCompleted,
    required dynamic Function(String)? onError,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSceneDescriptionStream,
          [],
          {
            #chapterContent: chapterContent,
            #characters: characters,
            #onChunk: onChunk,
            #onCompleted: onCompleted,
            #onError: onError,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>?> generateImmersiveScript({
    required String? chapterContent,
    required List<_i4.Character>? characters,
    required String? userInput,
    required String? userChoiceRole,
    String? existingPlay,
    List<Map<String, dynamic>>? existingRoleStrategy,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateImmersiveScript,
          [],
          {
            #chapterContent: chapterContent,
            #characters: characters,
            #userInput: userInput,
            #userChoiceRole: userChoiceRole,
            #existingPlay: existingPlay,
            #existingRoleStrategy: existingRoleStrategy,
          },
        ),
        returnValue: _i8.Future<Map<String, dynamic>?>.value(),
      ) as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<_i17.AICompanionResponse?> generateAICompanion({
    required String? chaptersContent,
    required String? backgroundSetting,
    required List<_i4.Character>? characters,
    required List<_i13.CharacterRelationship>? relationships,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAICompanion,
          [],
          {
            #chaptersContent: chaptersContent,
            #backgroundSetting: backgroundSetting,
            #characters: characters,
            #relationships: relationships,
          },
        ),
        returnValue: _i8.Future<_i17.AICompanionResponse?>.value(),
      ) as _i8.Future<_i17.AICompanionResponse?>);
}
