// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/core/providers/bookshelf_mutation_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:novel_app/core/interfaces/repositories/i_novel_repository.dart'
    as _i2;
import 'package:novel_app/models/novel.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [INovelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockINovelRepository extends _i1.Mock implements _i2.INovelRepository {
  MockINovelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Novel>> getNovels() => (super.noSuchMethod(
        Invocation.method(
          #getNovels,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Novel>>.value(<_i4.Novel>[]),
      ) as _i3.Future<List<_i4.Novel>>);

  @override
  _i3.Future<bool> isInBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #isInBookshelf,
          [novelUrl],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> updateLastReadChapter(
    String? novelUrl,
    int? chapterIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastReadChapter,
          [
            novelUrl,
            chapterIndex,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateBackgroundSetting(
    String? novelUrl,
    String? backgroundSetting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSetting,
          [
            novelUrl,
            backgroundSetting,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<String?> getBackgroundSetting(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackgroundSetting,
          [novelUrl],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<int> getLastReadChapter(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #getLastReadChapter,
          [novelUrl],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i4.Novel?> getNovelByTitle(String? title) => (super.noSuchMethod(
        Invocation.method(
          #getNovelByTitle,
          [title],
        ),
        returnValue: _i3.Future<_i4.Novel?>.value(),
      ) as _i3.Future<_i4.Novel?>);

  @override
  _i3.Future<_i4.Novel?> getNovelByUrl(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #getNovelByUrl,
          [novelUrl],
        ),
        returnValue: _i3.Future<_i4.Novel?>.value(),
      ) as _i3.Future<_i4.Novel?>);

  @override
  _i3.Future<_i4.Novel?> getNovelById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getNovelById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Novel?>.value(),
      ) as _i3.Future<_i4.Novel?>);

  @override
  _i3.Future<String?> getNovelUrlById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getNovelUrlById,
          [id],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<int> updateBackgroundSettingById(
    int? id,
    String? setting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSettingById,
          [
            id,
            setting,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateCoverMediaIdById(
    int? id,
    String? mediaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCoverMediaIdById,
          [
            id,
            mediaId,
          ],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
