// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/screens/bookshelf_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:novel_app/models/ai_accompaniment_settings.dart' as _i3;
import 'package:novel_app/models/ai_companion_response.dart' as _i9;
import 'package:novel_app/models/bookshelf.dart' as _i14;
import 'package:novel_app/models/chapter.dart' as _i8;
import 'package:novel_app/models/character.dart' as _i4;
import 'package:novel_app/models/character_relationship.dart' as _i10;
import 'package:novel_app/models/chat_scene.dart' as _i13;
import 'package:novel_app/models/novel.dart' as _i7;
import 'package:novel_app/models/outline.dart' as _i12;
import 'package:novel_app/models/scene_illustration.dart' as _i11;
import 'package:novel_app/models/search_result.dart' as _i15;
import 'package:novel_app/repositories/bookshelf_repository.dart' as _i16;
import 'package:novel_app/services/database_service.dart' as _i5;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAiAccompanimentSettings_1 extends _i1.SmartFake
    implements _i3.AiAccompanimentSettings {
  _FakeAiAccompanimentSettings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCharacter_2 extends _i1.SmartFake implements _i4.Character {
  _FakeCharacter_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i5.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isWebPlatform => (super.noSuchMethod(
        Invocation.getter(#isWebPlatform),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i6.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i6.Future<_i2.Database>);

  @override
  _i6.Future<int> addToBookshelf(_i7.Novel? novel) => (super.noSuchMethod(
        Invocation.method(
          #addToBookshelf,
          [novel],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> createCustomNovel(
    String? title,
    String? author, {
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomNovel,
          [
            title,
            author,
          ],
          {#description: description},
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> removeFromBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeFromBookshelf,
          [novelUrl],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i7.Novel>> getBookshelf() => (super.noSuchMethod(
        Invocation.method(
          #getBookshelf,
          [],
        ),
        returnValue: _i6.Future<List<_i7.Novel>>.value(<_i7.Novel>[]),
      ) as _i6.Future<List<_i7.Novel>>);

  @override
  _i6.Future<List<_i7.Novel>> getNovels() => (super.noSuchMethod(
        Invocation.method(
          #getNovels,
          [],
        ),
        returnValue: _i6.Future<List<_i7.Novel>>.value(<_i7.Novel>[]),
      ) as _i6.Future<List<_i7.Novel>>);

  @override
  _i6.Future<bool> isInBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #isInBookshelf,
          [novelUrl],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> updateLastReadChapter(
    String? novelUrl,
    int? chapterIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastReadChapter,
          [
            novelUrl,
            chapterIndex,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> updateBackgroundSetting(
    String? novelUrl,
    String? backgroundSetting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSetting,
          [
            novelUrl,
            backgroundSetting,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> appendBackgroundSetting(
    String? novelUrl,
    String? newBackground,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #appendBackgroundSetting,
          [
            novelUrl,
            newBackground,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<String?> getBackgroundSetting(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackgroundSetting,
          [novelUrl],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<int> getLastReadChapter(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #getLastReadChapter,
          [novelUrl],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<_i3.AiAccompanimentSettings> getAiAccompanimentSettings(
          String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAiAccompanimentSettings,
          [novelUrl],
        ),
        returnValue: _i6.Future<_i3.AiAccompanimentSettings>.value(
            _FakeAiAccompanimentSettings_1(
          this,
          Invocation.method(
            #getAiAccompanimentSettings,
            [novelUrl],
          ),
        )),
      ) as _i6.Future<_i3.AiAccompanimentSettings>);

  @override
  _i6.Future<int> updateAiAccompanimentSettings(
    String? novelUrl,
    _i3.AiAccompanimentSettings? settings,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAiAccompanimentSettings,
          [
            novelUrl,
            settings,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> isChapterCached(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isChapterCached,
          [chapterUrl],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<String>> filterUncachedChapters(List<String>? chapterUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterUncachedChapters,
          [chapterUrls],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<Map<String, bool>> getChaptersCacheStatus(
          List<String>? chapterUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChaptersCacheStatus,
          [chapterUrls],
        ),
        returnValue: _i6.Future<Map<String, bool>>.value(<String, bool>{}),
      ) as _i6.Future<Map<String, bool>>);

  @override
  void markAsPreloading(String? chapterUrl) => super.noSuchMethod(
        Invocation.method(
          #markAsPreloading,
          [chapterUrl],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isPreloading(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isPreloading,
          [chapterUrl],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearMemoryState() => super.noSuchMethod(
        Invocation.method(
          #clearMemoryState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<int> cacheChapter(
    String? novelUrl,
    _i8.Chapter? chapter,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheChapter,
          [
            novelUrl,
            chapter,
            content,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> updateChapterContent(
    String? chapterUrl,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChapterContent,
          [
            chapterUrl,
            content,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> deleteChapterCache(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteChapterCache,
          [chapterUrl],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<String?> getCachedChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapter,
          [chapterUrl],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<String?> getChapterContent(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapterContent,
          [chapterUrl],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<List<_i8.Chapter>> getCachedChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapters,
          [novelUrl],
        ),
        returnValue: _i6.Future<List<_i8.Chapter>>.value(<_i8.Chapter>[]),
      ) as _i6.Future<List<_i8.Chapter>>);

  @override
  _i6.Future<int> deleteCachedChapters(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteCachedChapters,
          [novelUrl],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> clearNovelCache(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #clearNovelCache,
          [novelUrl],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> markChapterAsRead(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markChapterAsRead,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> getCachedChaptersCount(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChaptersCount,
          [novelUrl],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> isChapterAccompanied(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isChapterAccompanied,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> markChapterAsAccompanied(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markChapterAsAccompanied,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetChapterAccompaniedFlag(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetChapterAccompaniedFlag,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cacheNovelChapters(
    String? novelUrl,
    List<_i8.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheNovelChapters,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.Chapter>> getCachedNovelChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNovelChapters,
          [novelUrl],
        ),
        returnValue: _i6.Future<List<_i8.Chapter>>.value(<_i8.Chapter>[]),
      ) as _i6.Future<List<_i8.Chapter>>);

  @override
  _i6.Future<List<_i8.Chapter>> getChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapters,
          [novelUrl],
        ),
        returnValue: _i6.Future<List<_i8.Chapter>>.value(<_i8.Chapter>[]),
      ) as _i6.Future<List<_i8.Chapter>>);

  @override
  _i6.Future<void> updateChaptersOrder(
    String? novelUrl,
    List<_i8.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChaptersOrder,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> createCustomChapter(
    String? novelUrl,
    String? title,
    String? content, [
    int? index,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomChapter,
          [
            novelUrl,
            title,
            content,
            index,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> insertUserChapter(
    String? novelUrl,
    String? title,
    String? content, [
    int? index,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertUserChapter,
          [
            novelUrl,
            title,
            content,
            index,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> updateCustomChapter(
    String? chapterUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomChapter,
          [
            chapterUrl,
            title,
            content,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteCustomChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomChapter,
          [chapterUrl],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUserChapter(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteUserChapter,
          [chapterUrl],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> createCharacter(_i4.Character? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCharacter,
          [character],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i4.Character>> getCharacters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacters,
          [novelUrl],
        ),
        returnValue: _i6.Future<List<_i4.Character>>.value(<_i4.Character>[]),
      ) as _i6.Future<List<_i4.Character>>);

  @override
  _i6.Future<_i4.Character?> getCharacter(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getCharacter,
          [id],
        ),
        returnValue: _i6.Future<_i4.Character?>.value(),
      ) as _i6.Future<_i4.Character?>);

  @override
  _i6.Future<int> updateCharacter(_i4.Character? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacter,
          [character],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> deleteCharacter(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCharacter,
          [id],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<_i4.Character?> findCharacterByName(
    String? novelUrl,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCharacterByName,
          [
            novelUrl,
            name,
          ],
        ),
        returnValue: _i6.Future<_i4.Character?>.value(),
      ) as _i6.Future<_i4.Character?>);

  @override
  _i6.Future<_i4.Character> updateOrInsertCharacter(
          _i4.Character? newCharacter) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrInsertCharacter,
          [newCharacter],
        ),
        returnValue: _i6.Future<_i4.Character>.value(_FakeCharacter_2(
          this,
          Invocation.method(
            #updateOrInsertCharacter,
            [newCharacter],
          ),
        )),
      ) as _i6.Future<_i4.Character>);

  @override
  _i6.Future<List<_i4.Character>> batchUpdateCharacters(
          List<_i4.Character>? newCharacters) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateCharacters,
          [newCharacters],
        ),
        returnValue: _i6.Future<List<_i4.Character>>.value(<_i4.Character>[]),
      ) as _i6.Future<List<_i4.Character>>);

  @override
  _i6.Future<List<String>> getCharacterNames(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterNames,
          [novelUrl],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<bool> characterExists(int? id) => (super.noSuchMethod(
        Invocation.method(
          #characterExists,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i4.Character>> getCharactersByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharactersByIds,
          [ids],
        ),
        returnValue: _i6.Future<List<_i4.Character>>.value(<_i4.Character>[]),
      ) as _i6.Future<List<_i4.Character>>);

  @override
  _i6.Future<int> deleteAllCharacters(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllCharacters,
          [novelUrl],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> updateCharacterCachedImage(
    int? characterId,
    String? imageUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterCachedImage,
          [
            characterId,
            imageUrl,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> clearCharacterCachedImage(int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCharacterCachedImage,
          [characterId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> clearAllCharacterCachedImages(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearAllCharacterCachedImages,
          [novelUrl],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<String?> getCharacterCachedImage(int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterCachedImage,
          [characterId],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<int> updateCharacterAvatar(
    int? characterId, {
    String? imageUrl,
    String? originalFilename,
    String? originalImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterAvatar,
          [characterId],
          {
            #imageUrl: imageUrl,
            #originalFilename: originalFilename,
            #originalImageUrl: originalImageUrl,
          },
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> hasCharacterAvatar(int? characterId) => (super.noSuchMethod(
        Invocation.method(
          #hasCharacterAvatar,
          [characterId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> batchUpdateOrInsertCharacters(
    String? novelUrl,
    List<_i9.AICompanionRole>? aiRoles,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateOrInsertCharacters,
          [
            novelUrl,
            aiRoles,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> createRelationship(
          _i10.CharacterRelationship? relationship) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRelationship,
          [relationship],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i10.CharacterRelationship>> getRelationships(
          int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelationships,
          [characterId],
        ),
        returnValue: _i6.Future<List<_i10.CharacterRelationship>>.value(
            <_i10.CharacterRelationship>[]),
      ) as _i6.Future<List<_i10.CharacterRelationship>>);

  @override
  _i6.Future<List<_i10.CharacterRelationship>> getOutgoingRelationships(
          int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOutgoingRelationships,
          [characterId],
        ),
        returnValue: _i6.Future<List<_i10.CharacterRelationship>>.value(
            <_i10.CharacterRelationship>[]),
      ) as _i6.Future<List<_i10.CharacterRelationship>>);

  @override
  _i6.Future<List<_i10.CharacterRelationship>> getIncomingRelationships(
          int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIncomingRelationships,
          [characterId],
        ),
        returnValue: _i6.Future<List<_i10.CharacterRelationship>>.value(
            <_i10.CharacterRelationship>[]),
      ) as _i6.Future<List<_i10.CharacterRelationship>>);

  @override
  _i6.Future<int> updateRelationship(
          _i10.CharacterRelationship? relationship) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRelationship,
          [relationship],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> deleteRelationship(int? relationshipId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRelationship,
          [relationshipId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> relationshipExists(
    int? sourceId,
    int? targetId,
    String? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #relationshipExists,
          [
            sourceId,
            targetId,
            type,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> getRelationshipCount(int? characterId) => (super.noSuchMethod(
        Invocation.method(
          #getRelationshipCount,
          [characterId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<int>> getRelatedCharacterIds(int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelatedCharacterIds,
          [characterId],
        ),
        returnValue: _i6.Future<List<int>>.value(<int>[]),
      ) as _i6.Future<List<int>>);

  @override
  _i6.Future<List<_i10.CharacterRelationship>> getAllRelationships(
          String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllRelationships,
          [novelUrl],
        ),
        returnValue: _i6.Future<List<_i10.CharacterRelationship>>.value(
            <_i10.CharacterRelationship>[]),
      ) as _i6.Future<List<_i10.CharacterRelationship>>);

  @override
  _i6.Future<List<_i10.CharacterRelationship>> getRelationshipsByCharacterIds(
    int? sourceId,
    int? targetId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRelationshipsByCharacterIds,
          [
            sourceId,
            targetId,
          ],
        ),
        returnValue: _i6.Future<List<_i10.CharacterRelationship>>.value(
            <_i10.CharacterRelationship>[]),
      ) as _i6.Future<List<_i10.CharacterRelationship>>);

  @override
  _i6.Future<int> batchUpdateOrInsertRelationships(
    String? novelUrl,
    List<_i9.AICompanionRelation>? aiRelations,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateOrInsertRelationships,
          [
            novelUrl,
            aiRelations,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> insertSceneIllustration(
          _i11.SceneIllustration? illustration) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSceneIllustration,
          [illustration],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> updateSceneIllustrationStatus(
    int? id,
    String? status, {
    List<String>? images,
    String? prompts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSceneIllustrationStatus,
          [
            id,
            status,
          ],
          {
            #images: images,
            #prompts: prompts,
          },
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> deleteSceneIllustration(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSceneIllustration,
          [id],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> deleteSceneIllustrationsByChapter(
    String? novelUrl,
    String? chapterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSceneIllustrationsByChapter,
          [
            novelUrl,
            chapterId,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i11.SceneIllustration>> getSceneIllustrationsByChapter(
    String? novelUrl,
    String? chapterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationsByChapter,
          [
            novelUrl,
            chapterId,
          ],
        ),
        returnValue: _i6.Future<List<_i11.SceneIllustration>>.value(
            <_i11.SceneIllustration>[]),
      ) as _i6.Future<List<_i11.SceneIllustration>>);

  @override
  _i6.Future<_i11.SceneIllustration?> getSceneIllustrationByTaskId(
          String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationByTaskId,
          [taskId],
        ),
        returnValue: _i6.Future<_i11.SceneIllustration?>.value(),
      ) as _i6.Future<_i11.SceneIllustration?>);

  @override
  _i6.Future<Map<String, dynamic>> getSceneIllustrationsPaginated({
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationsPaginated,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i11.SceneIllustration>> getPendingSceneIllustrations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSceneIllustrations,
          [],
        ),
        returnValue: _i6.Future<List<_i11.SceneIllustration>>.value(
            <_i11.SceneIllustration>[]),
      ) as _i6.Future<List<_i11.SceneIllustration>>);

  @override
  _i6.Future<int> batchUpdateSceneIllustrations(
    List<int>? ids,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateSceneIllustrations,
          [
            ids,
            status,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> getIllustrationCount(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #getIllustrationCount,
          [novelUrl],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> getCompletedIllustrationCount(
    String? novelUrl,
    String? chapterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletedIllustrationCount,
          [
            novelUrl,
            chapterId,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> taskExists(String? taskId) => (super.noSuchMethod(
        Invocation.method(
          #taskExists,
          [taskId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<int> saveOutline(_i12.Outline? outline) => (super.noSuchMethod(
        Invocation.method(
          #saveOutline,
          [outline],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<_i12.Outline?> getOutlineByNovelUrl(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOutlineByNovelUrl,
          [novelUrl],
        ),
        returnValue: _i6.Future<_i12.Outline?>.value(),
      ) as _i6.Future<_i12.Outline?>);

  @override
  _i6.Future<List<_i12.Outline>> getAllOutlines() => (super.noSuchMethod(
        Invocation.method(
          #getAllOutlines,
          [],
        ),
        returnValue: _i6.Future<List<_i12.Outline>>.value(<_i12.Outline>[]),
      ) as _i6.Future<List<_i12.Outline>>);

  @override
  _i6.Future<int> deleteOutline(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteOutline,
          [novelUrl],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> updateOutlineContent(
    String? novelUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOutlineContent,
          [
            novelUrl,
            title,
            content,
          ],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<int> insertChatScene(_i13.ChatScene? scene) => (super.noSuchMethod(
        Invocation.method(
          #insertChatScene,
          [scene],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> updateChatScene(_i13.ChatScene? scene) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatScene,
          [scene],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteChatScene(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteChatScene,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i13.ChatScene>> getAllChatScenes() => (super.noSuchMethod(
        Invocation.method(
          #getAllChatScenes,
          [],
        ),
        returnValue: _i6.Future<List<_i13.ChatScene>>.value(<_i13.ChatScene>[]),
      ) as _i6.Future<List<_i13.ChatScene>>);

  @override
  _i6.Future<_i13.ChatScene?> getChatSceneById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getChatSceneById,
          [id],
        ),
        returnValue: _i6.Future<_i13.ChatScene?>.value(),
      ) as _i6.Future<_i13.ChatScene?>);

  @override
  _i6.Future<List<_i13.ChatScene>> searchChatScenes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchChatScenes,
          [query],
        ),
        returnValue: _i6.Future<List<_i13.ChatScene>>.value(<_i13.ChatScene>[]),
      ) as _i6.Future<List<_i13.ChatScene>>);

  @override
  _i6.Future<List<_i14.Bookshelf>> getBookshelves() => (super.noSuchMethod(
        Invocation.method(
          #getBookshelves,
          [],
        ),
        returnValue: _i6.Future<List<_i14.Bookshelf>>.value(<_i14.Bookshelf>[]),
      ) as _i6.Future<List<_i14.Bookshelf>>);

  @override
  _i6.Future<int> createBookshelf(String? name) => (super.noSuchMethod(
        Invocation.method(
          #createBookshelf,
          [name],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> deleteBookshelf(int? bookshelfId) => (super.noSuchMethod(
        Invocation.method(
          #deleteBookshelf,
          [bookshelfId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i7.Novel>> getNovelsByBookshelf(int? bookshelfId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNovelsByBookshelf,
          [bookshelfId],
        ),
        returnValue: _i6.Future<List<_i7.Novel>>.value(<_i7.Novel>[]),
      ) as _i6.Future<List<_i7.Novel>>);

  @override
  _i6.Future<void> addNovelToBookshelf(
    String? novelUrl,
    int? bookshelfId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNovelToBookshelf,
          [
            novelUrl,
            bookshelfId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> removeNovelFromBookshelf(
    String? novelUrl,
    int? bookshelfId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeNovelFromBookshelf,
          [
            novelUrl,
            bookshelfId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> moveNovelToBookshelf(
    String? novelUrl,
    int? fromBookshelfId,
    int? toBookshelfId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveNovelToBookshelf,
          [
            novelUrl,
            fromBookshelfId,
            toBookshelfId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<int>> getBookshelvesByNovel(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookshelvesByNovel,
          [novelUrl],
        ),
        returnValue: _i6.Future<List<int>>.value(<int>[]),
      ) as _i6.Future<List<int>>);

  @override
  _i6.Future<int> getNovelCountByBookshelf(int? bookshelfId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNovelCountByBookshelf,
          [bookshelfId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> isNovelInBookshelf(
    String? novelUrl,
    int? bookshelfId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isNovelInBookshelf,
          [
            novelUrl,
            bookshelfId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> reorderBookshelves(List<int>? bookshelfIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderBookshelves,
          [bookshelfIds],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> updateBookshelf(_i14.Bookshelf? bookshelf) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookshelf,
          [bookshelf],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i15.ChapterSearchResult>> searchInCachedContent(
    String? keyword, {
    String? novelUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchInCachedContent,
          [keyword],
          {#novelUrl: novelUrl},
        ),
        returnValue: _i6.Future<List<_i15.ChapterSearchResult>>.value(
            <_i15.ChapterSearchResult>[]),
      ) as _i6.Future<List<_i15.ChapterSearchResult>>);

  @override
  _i6.Future<List<_i15.CachedNovelInfo>> getCachedNovels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNovels,
          [],
        ),
        returnValue: _i6.Future<List<_i15.CachedNovelInfo>>.value(
            <_i15.CachedNovelInfo>[]),
      ) as _i6.Future<List<_i15.CachedNovelInfo>>);
}

/// A class which mocks [BookshelfRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookshelfRepository extends _i1.Mock
    implements _i16.BookshelfRepository {
  MockBookshelfRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i6.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i6.Future<_i2.Database>);

  @override
  bool get isWebPlatform => (super.noSuchMethod(
        Invocation.getter(#isWebPlatform),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<_i2.Database> initDatabase() => (super.noSuchMethod(
        Invocation.method(
          #initDatabase,
          [],
        ),
        returnValue: _i6.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.method(
            #initDatabase,
            [],
          ),
        )),
      ) as _i6.Future<_i2.Database>);

  @override
  _i6.Future<List<_i14.Bookshelf>> getBookshelves() => (super.noSuchMethod(
        Invocation.method(
          #getBookshelves,
          [],
        ),
        returnValue: _i6.Future<List<_i14.Bookshelf>>.value(<_i14.Bookshelf>[]),
      ) as _i6.Future<List<_i14.Bookshelf>>);

  @override
  _i6.Future<int> createBookshelf(String? name) => (super.noSuchMethod(
        Invocation.method(
          #createBookshelf,
          [name],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> deleteBookshelf(int? bookshelfId) => (super.noSuchMethod(
        Invocation.method(
          #deleteBookshelf,
          [bookshelfId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i7.Novel>> getNovelsByBookshelf(int? bookshelfId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNovelsByBookshelf,
          [bookshelfId],
        ),
        returnValue: _i6.Future<List<_i7.Novel>>.value(<_i7.Novel>[]),
      ) as _i6.Future<List<_i7.Novel>>);

  @override
  _i6.Future<void> addNovelToBookshelf(
    String? novelUrl,
    int? bookshelfId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNovelToBookshelf,
          [
            novelUrl,
            bookshelfId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> removeNovelFromBookshelf(
    String? novelUrl,
    int? bookshelfId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeNovelFromBookshelf,
          [
            novelUrl,
            bookshelfId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> moveNovelToBookshelf(
    String? novelUrl,
    int? fromBookshelfId,
    int? toBookshelfId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveNovelToBookshelf,
          [
            novelUrl,
            fromBookshelfId,
            toBookshelfId,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<int>> getBookshelvesByNovel(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookshelvesByNovel,
          [novelUrl],
        ),
        returnValue: _i6.Future<List<int>>.value(<int>[]),
      ) as _i6.Future<List<int>>);

  @override
  _i6.Future<int> getNovelCountByBookshelf(int? bookshelfId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNovelCountByBookshelf,
          [bookshelfId],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> isNovelInBookshelf(
    String? novelUrl,
    int? bookshelfId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isNovelInBookshelf,
          [
            novelUrl,
            bookshelfId,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> reorderBookshelves(List<int>? bookshelfIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderBookshelves,
          [bookshelfIds],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> updateBookshelf(_i14.Bookshelf? bookshelf) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookshelf,
          [bookshelf],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  void setSharedDatabase(_i2.Database? database) => super.noSuchMethod(
        Invocation.method(
          #setSharedDatabase,
          [database],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
