// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/screens/chat_scene_management_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:novel_app/models/chat_scene.dart' as _i5;
import 'package:novel_app/repositories/chat_scene_repository.dart' as _i3;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ChatSceneRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatSceneRepository extends _i1.Mock
    implements _i3.ChatSceneRepository {
  MockChatSceneRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  bool get isWebPlatform => (super.noSuchMethod(
        Invocation.getter(#isWebPlatform),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<_i2.Database> initDatabase() => (super.noSuchMethod(
        Invocation.method(
          #initDatabase,
          [],
        ),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.method(
            #initDatabase,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<int> insertChatScene(_i5.ChatScene? scene) => (super.noSuchMethod(
        Invocation.method(
          #insertChatScene,
          [scene],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> updateChatScene(_i5.ChatScene? scene) => (super.noSuchMethod(
        Invocation.method(
          #updateChatScene,
          [scene],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteChatScene(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteChatScene,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.ChatScene>> getAllChatScenes() => (super.noSuchMethod(
        Invocation.method(
          #getAllChatScenes,
          [],
        ),
        returnValue: _i4.Future<List<_i5.ChatScene>>.value(<_i5.ChatScene>[]),
      ) as _i4.Future<List<_i5.ChatScene>>);

  @override
  _i4.Future<_i5.ChatScene?> getChatSceneById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getChatSceneById,
          [id],
        ),
        returnValue: _i4.Future<_i5.ChatScene?>.value(),
      ) as _i4.Future<_i5.ChatScene?>);

  @override
  _i4.Future<List<_i5.ChatScene>> searchChatScenes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchChatScenes,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.ChatScene>>.value(<_i5.ChatScene>[]),
      ) as _i4.Future<List<_i5.ChatScene>>);

  @override
  void setSharedDatabase(_i2.Database? database) => super.noSuchMethod(
        Invocation.method(
          #setSharedDatabase,
          [database],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
