"""Add text2img chapter illustrations table

Revision ID: 262daff792e5
Revises: 0854456d220e
Create Date: 2025-12-11 02:47:09.709432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '262daff792e5'
down_revision = '0854456d220e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create chapter_illustrations table for text2img functionality
    op.create_table('chapter_illustrations',
        sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
        sa.Column('chapter_id', sa.String(length=255), nullable=False, comment='章节ID'),
        sa.Column('status', sa.String(length=50), nullable=False, comment='任务状态'),
        sa.Column('total_images', sa.Integer(), nullable=True, comment='需要生成的图片总数'),
        sa.Column('completed_images', sa.Integer(), nullable=True, comment='已完成的图片数量'),
        sa.Column('novel_content', sa.Text(), nullable=True, comment='小说内容'),
        sa.Column('roles', sa.JSON(), nullable=True, comment='角色信息'),
        sa.Column('require', sa.Text(), nullable=True, comment='配图要求'),
        sa.Column('image_data', sa.JSON(), nullable=True, comment='图片生成结果数据'),
        sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('chapter_id')
    )
    op.create_index(op.f('ix_chapter_illustrations_chapter_id'), 'chapter_illustrations', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_illustrations_id'), 'chapter_illustrations', ['id'], unique=False)
    op.create_index('ix_chapter_illustrations_chapter_id_unique', 'chapter_illustrations', ['chapter_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chapter_illustrations_chapter_id_unique', table_name='chapter_illustrations')
    op.drop_index(op.f('ix_chapter_illustrations_id'), table_name='chapter_illustrations')
    op.drop_index(op.f('ix_chapter_illustrations_chapter_id'), table_name='chapter_illustrations')
    op.drop_table('chapter_illustrations')
    # ### end Alembic commands ###