"""Allow task_id to be nullable for individual chapters

Revision ID: 69a1dfa2484c
Revises: e7b3ba19a7f3
Create Date: 2025-12-17 16:01:58.987216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a1dfa2484c'
down_revision = 'e7b3ba19a7f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('novel_chapters_cache', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('role_card_tasks', 'user_input',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='用户要求',
               existing_server_default=sa.text("'生成人物卡'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_card_tasks', 'user_input',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='用户要求',
               existing_server_default=sa.text("'生成人物卡'::text"))
    op.alter_column('novel_chapters_cache', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###