"""Initial schema - unified model definitions

Revision ID: fa0c8cbd60d7
Revises: 
Create Date: 2025-12-16 07:14:09.049045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa0c8cbd60d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_novel_cache_tasks_id'), table_name='novel_cache_tasks')
    op.drop_index(op.f('idx_novel_cache_tasks_novel_url'), table_name='novel_cache_tasks')
    op.drop_index(op.f('idx_novel_cache_tasks_status'), table_name='novel_cache_tasks')
    op.create_index(op.f('ix_novel_cache_tasks_id'), 'novel_cache_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_novel_cache_tasks_novel_url'), 'novel_cache_tasks', ['novel_url'], unique=False)
    op.create_index(op.f('ix_novel_cache_tasks_status'), 'novel_cache_tasks', ['status'], unique=False)
    op.drop_index(op.f('idx_novel_chapters_cache_chapter_index'), table_name='novel_chapters_cache')
    op.drop_index(op.f('idx_novel_chapters_cache_id'), table_name='novel_chapters_cache')
    op.drop_index(op.f('idx_novel_chapters_cache_task_id'), table_name='novel_chapters_cache')
    op.create_index(op.f('ix_novel_chapters_cache_id'), 'novel_chapters_cache', ['id'], unique=False)
    op.create_index(op.f('ix_novel_chapters_cache_novel_url'), 'novel_chapters_cache', ['novel_url'], unique=False)
    op.drop_constraint(op.f('novel_chapters_cache_task_id_fkey'), 'novel_chapters_cache', type_='foreignkey')
    op.create_foreign_key(None, 'novel_chapters_cache', 'novel_cache_tasks', ['task_id'], ['id'])
    op.alter_column('role_image_gallery', 'video_status',
               existing_type=sa.VARCHAR(length=20),
               comment='视频生成状态: none/pending/running/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('role_image_gallery', 'video_filename',
               existing_type=sa.VARCHAR(length=500),
               comment='生成的视频文件名',
               existing_nullable=True)
    op.alter_column('role_image_gallery', 'video_prompt',
               existing_type=sa.TEXT(),
               comment='视频生成提示词',
               existing_nullable=True)
    op.alter_column('role_image_gallery', 'video_created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='视频创建时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_image_gallery', 'video_created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='视频创建时间',
               existing_nullable=True)
    op.alter_column('role_image_gallery', 'video_prompt',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='视频生成提示词',
               existing_nullable=True)
    op.alter_column('role_image_gallery', 'video_filename',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='生成的视频文件名',
               existing_nullable=True)
    op.alter_column('role_image_gallery', 'video_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='视频生成状态: none/pending/running/completed/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.drop_constraint(None, 'novel_chapters_cache', type_='foreignkey')
    op.create_foreign_key(op.f('novel_chapters_cache_task_id_fkey'), 'novel_chapters_cache', 'novel_cache_tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_novel_chapters_cache_novel_url'), table_name='novel_chapters_cache')
    op.drop_index(op.f('ix_novel_chapters_cache_id'), table_name='novel_chapters_cache')
    op.create_index(op.f('idx_novel_chapters_cache_task_id'), 'novel_chapters_cache', ['task_id'], unique=False)
    op.create_index(op.f('idx_novel_chapters_cache_id'), 'novel_chapters_cache', ['id'], unique=False)
    op.create_index(op.f('idx_novel_chapters_cache_chapter_index'), 'novel_chapters_cache', ['chapter_index'], unique=False)
    op.drop_index(op.f('ix_novel_cache_tasks_status'), table_name='novel_cache_tasks')
    op.drop_index(op.f('ix_novel_cache_tasks_novel_url'), table_name='novel_cache_tasks')
    op.drop_index(op.f('ix_novel_cache_tasks_id'), table_name='novel_cache_tasks')
    op.create_index(op.f('idx_novel_cache_tasks_status'), 'novel_cache_tasks', ['status'], unique=False)
    op.create_index(op.f('idx_novel_cache_tasks_novel_url'), 'novel_cache_tasks', ['novel_url'], unique=False)
    op.create_index(op.f('idx_novel_cache_tasks_id'), 'novel_cache_tasks', ['id'], unique=False)
    # ### end Alembic commands ###