// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/services/api_service_wrapper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i18;

import 'package:built_collection/built_collection.dart' as _i12;
import 'package:built_value/json_object.dart' as _i15;
import 'package:dio/dio.dart' as _i7;
import 'package:dio/src/adapter.dart' as _i3;
import 'package:dio/src/cancel_token.dart' as _i9;
import 'package:dio/src/dio_mixin.dart' as _i5;
import 'package:dio/src/options.dart' as _i2;
import 'package:dio/src/response.dart' as _i6;
import 'package:dio/src/transformer.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:novel_api/src/api/default_api.dart' as _i10;
import 'package:novel_api/src/model/app_version_response.dart' as _i23;
import 'package:novel_api/src/model/chapter.dart' as _i13;
import 'package:novel_api/src/model/chapter_content.dart' as _i11;
import 'package:novel_api/src/model/enhanced_scene_illustration_request.dart'
    as _i20;
import 'package:novel_api/src/model/image_to_video_request.dart' as _i22;
import 'package:novel_api/src/model/image_to_video_response.dart' as _i21;
import 'package:novel_api/src/model/models_response.dart' as _i24;
import 'package:novel_api/src/model/novel.dart' as _i32;
import 'package:novel_api/src/model/role_card_generate_request.dart' as _i19;
import 'package:novel_api/src/model/role_card_task_status_response.dart'
    as _i26;
import 'package:novel_api/src/model/role_gallery_response.dart' as _i25;
import 'package:novel_api/src/model/role_image_delete_request.dart' as _i16;
import 'package:novel_api/src/model/role_regenerate_request.dart' as _i31;
import 'package:novel_api/src/model/scene_gallery_response.dart' as _i27;
import 'package:novel_api/src/model/scene_image_delete_request.dart' as _i17;
import 'package:novel_api/src/model/scene_regenerate_request.dart' as _i30;
import 'package:novel_api/src/model/scene_regenerate_response.dart' as _i29;
import 'package:novel_api/src/model/source_site.dart' as _i28;
import 'package:novel_api/src/model/video_status_response.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseOptions_0 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_1 extends _i1.SmartFake
    implements _i3.HttpClientAdapter {
  _FakeHttpClientAdapter_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_2 extends _i1.SmartFake implements _i4.Transformer {
  _FakeTransformer_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_3 extends _i1.SmartFake implements _i5.Interceptors {
  _FakeInterceptors_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4<T1> extends _i1.SmartFake implements _i6.Response<T1> {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i7.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_0(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.BaseOptions);

  @override
  _i3.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_1(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i3.HttpClientAdapter);

  @override
  _i4.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_2(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i4.Transformer);

  @override
  _i5.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_3(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i5.Interceptors);

  @override
  set options(_i2.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set httpClientAdapter(_i3.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set transformer(_i4.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i6.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i9.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i9.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i8.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<dynamic>>);

  @override
  _i8.Future<_i6.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i9.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i8.Future<_i6.Response<dynamic>>.value(_FakeResponse_4<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<dynamic>>);

  @override
  _i8.Future<_i6.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i9.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i9.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i8.Future<_i6.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i8.Future<_i6.Response<T>>.value(_FakeResponse_4<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i8.Future<_i6.Response<T>>);

  @override
  _i7.Dio clone({
    _i2.BaseOptions? options,
    _i5.Interceptors? interceptors,
    _i3.HttpClientAdapter? httpClientAdapter,
    _i4.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
          {
            #options: options,
            #interceptors: interceptors,
            #httpClientAdapter: httpClientAdapter,
            #transformer: transformer,
          },
        ),
        returnValue: _FakeDio_5(
          this,
          Invocation.method(
            #clone,
            [],
            {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            },
          ),
        ),
      ) as _i7.Dio);
}

/// A class which mocks [DefaultApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDefaultApi extends _i1.Mock implements _i10.DefaultApi {
  MockDefaultApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.Response<_i11.ChapterContent>>
      chapterContentChapterContentGet({
    required String? url,
    bool? forceRefresh = false,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #chapterContentChapterContentGet,
              [],
              {
                #url: url,
                #forceRefresh: forceRefresh,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i11.ChapterContent>>.value(
                _FakeResponse_4<_i11.ChapterContent>(
              this,
              Invocation.method(
                #chapterContentChapterContentGet,
                [],
                {
                  #url: url,
                  #forceRefresh: forceRefresh,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i11.ChapterContent>>);

  @override
  _i8.Future<_i6.Response<_i12.BuiltList<_i13.Chapter>>> chaptersChaptersGet({
    required String? url,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #chaptersChaptersGet,
          [],
          {
            #url: url,
            #X_API_TOKEN: X_API_TOKEN,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i8.Future<_i6.Response<_i12.BuiltList<_i13.Chapter>>>.value(
                _FakeResponse_4<_i12.BuiltList<_i13.Chapter>>(
          this,
          Invocation.method(
            #chaptersChaptersGet,
            [],
            {
              #url: url,
              #X_API_TOKEN: X_API_TOKEN,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<_i12.BuiltList<_i13.Chapter>>>);

  @override
  _i8.Future<_i6.Response<_i14.VideoStatusResponse>>
      checkVideoStatusApiImageToVideoHasVideoImgNameGet({
    required String? imgName,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #checkVideoStatusApiImageToVideoHasVideoImgNameGet,
              [],
              {
                #imgName: imgName,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue:
                _i8.Future<_i6.Response<_i14.VideoStatusResponse>>.value(
                    _FakeResponse_4<_i14.VideoStatusResponse>(
              this,
              Invocation.method(
                #checkVideoStatusApiImageToVideoHasVideoImgNameGet,
                [],
                {
                  #imgName: imgName,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i14.VideoStatusResponse>>);

  @override
  _i8.Future<_i6.Response<_i15.JsonObject>>
      deleteRoleCardImageApiRoleCardImageDelete({
    required _i16.RoleImageDeleteRequest? roleImageDeleteRequest,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #deleteRoleCardImageApiRoleCardImageDelete,
              [],
              {
                #roleImageDeleteRequest: roleImageDeleteRequest,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i15.JsonObject>>.value(
                _FakeResponse_4<_i15.JsonObject>(
              this,
              Invocation.method(
                #deleteRoleCardImageApiRoleCardImageDelete,
                [],
                {
                  #roleImageDeleteRequest: roleImageDeleteRequest,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i15.JsonObject>>);

  @override
  _i8.Future<_i6.Response<_i15.JsonObject>>
      deleteSceneImageApiSceneIllustrationImageDelete({
    required _i17.SceneImageDeleteRequest? sceneImageDeleteRequest,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #deleteSceneImageApiSceneIllustrationImageDelete,
              [],
              {
                #sceneImageDeleteRequest: sceneImageDeleteRequest,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i15.JsonObject>>.value(
                _FakeResponse_4<_i15.JsonObject>(
              this,
              Invocation.method(
                #deleteSceneImageApiSceneIllustrationImageDelete,
                [],
                {
                  #sceneImageDeleteRequest: sceneImageDeleteRequest,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i15.JsonObject>>);

  @override
  _i8.Future<_i6.Response<_i18.Uint8List>>
      downloadAppVersionApiAppVersionDownloadVersionGet({
    required String? version,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #downloadAppVersionApiAppVersionDownloadVersionGet,
              [],
              {
                #version: version,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i18.Uint8List>>.value(
                _FakeResponse_4<_i18.Uint8List>(
              this,
              Invocation.method(
                #downloadAppVersionApiAppVersionDownloadVersionGet,
                [],
                {
                  #version: version,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i18.Uint8List>>);

  @override
  _i8.Future<_i6.Response<_i15.JsonObject>>
      generateRoleCardImagesApiRoleCardGeneratePost({
    required _i19.RoleCardGenerateRequest? roleCardGenerateRequest,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #generateRoleCardImagesApiRoleCardGeneratePost,
              [],
              {
                #roleCardGenerateRequest: roleCardGenerateRequest,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i15.JsonObject>>.value(
                _FakeResponse_4<_i15.JsonObject>(
              this,
              Invocation.method(
                #generateRoleCardImagesApiRoleCardGeneratePost,
                [],
                {
                  #roleCardGenerateRequest: roleCardGenerateRequest,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i15.JsonObject>>);

  @override
  _i8.Future<_i6.Response<_i15.JsonObject>>
      generateSceneImagesApiSceneIllustrationGeneratePost({
    required _i20.EnhancedSceneIllustrationRequest?
        enhancedSceneIllustrationRequest,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #generateSceneImagesApiSceneIllustrationGeneratePost,
              [],
              {
                #enhancedSceneIllustrationRequest:
                    enhancedSceneIllustrationRequest,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i15.JsonObject>>.value(
                _FakeResponse_4<_i15.JsonObject>(
              this,
              Invocation.method(
                #generateSceneImagesApiSceneIllustrationGeneratePost,
                [],
                {
                  #enhancedSceneIllustrationRequest:
                      enhancedSceneIllustrationRequest,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i15.JsonObject>>);

  @override
  _i8.Future<_i6.Response<_i21.ImageToVideoResponse>>
      generateVideoFromImageApiImageToVideoGeneratePost({
    required _i22.ImageToVideoRequest? imageToVideoRequest,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #generateVideoFromImageApiImageToVideoGeneratePost,
              [],
              {
                #imageToVideoRequest: imageToVideoRequest,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue:
                _i8.Future<_i6.Response<_i21.ImageToVideoResponse>>.value(
                    _FakeResponse_4<_i21.ImageToVideoResponse>(
              this,
              Invocation.method(
                #generateVideoFromImageApiImageToVideoGeneratePost,
                [],
                {
                  #imageToVideoRequest: imageToVideoRequest,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i21.ImageToVideoResponse>>);

  @override
  _i8.Future<_i6.Response<_i18.Uint8List>>
      getImageProxyText2imgImageFilenameGet({
    required String? filename,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getImageProxyText2imgImageFilenameGet,
              [],
              {
                #filename: filename,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i18.Uint8List>>.value(
                _FakeResponse_4<_i18.Uint8List>(
              this,
              Invocation.method(
                #getImageProxyText2imgImageFilenameGet,
                [],
                {
                  #filename: filename,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i18.Uint8List>>);

  @override
  _i8.Future<_i6.Response<_i23.AppVersionResponse>>
      getLatestAppVersionApiAppVersionLatestGet({
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getLatestAppVersionApiAppVersionLatestGet,
              [],
              {
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue:
                _i8.Future<_i6.Response<_i23.AppVersionResponse>>.value(
                    _FakeResponse_4<_i23.AppVersionResponse>(
              this,
              Invocation.method(
                #getLatestAppVersionApiAppVersionLatestGet,
                [],
                {
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i23.AppVersionResponse>>);

  @override
  _i8.Future<_i6.Response<_i24.ModelsResponse>> getModelsApiModelsGet({
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModelsApiModelsGet,
          [],
          {
            #X_API_TOKEN: X_API_TOKEN,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<_i24.ModelsResponse>>.value(
            _FakeResponse_4<_i24.ModelsResponse>(
          this,
          Invocation.method(
            #getModelsApiModelsGet,
            [],
            {
              #X_API_TOKEN: X_API_TOKEN,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<_i24.ModelsResponse>>);

  @override
  _i8.Future<_i6.Response<_i25.RoleGalleryResponse>>
      getRoleCardGalleryApiRoleCardGalleryRoleIdGet({
    required String? roleId,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRoleCardGalleryApiRoleCardGalleryRoleIdGet,
              [],
              {
                #roleId: roleId,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue:
                _i8.Future<_i6.Response<_i25.RoleGalleryResponse>>.value(
                    _FakeResponse_4<_i25.RoleGalleryResponse>(
              this,
              Invocation.method(
                #getRoleCardGalleryApiRoleCardGalleryRoleIdGet,
                [],
                {
                  #roleId: roleId,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i25.RoleGalleryResponse>>);

  @override
  _i8.Future<_i6.Response<_i26.RoleCardTaskStatusResponse>>
      getRoleCardTaskStatusApiRoleCardStatusTaskIdGet({
    required int? taskId,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRoleCardTaskStatusApiRoleCardStatusTaskIdGet,
              [],
              {
                #taskId: taskId,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue:
                _i8.Future<_i6.Response<_i26.RoleCardTaskStatusResponse>>.value(
                    _FakeResponse_4<_i26.RoleCardTaskStatusResponse>(
              this,
              Invocation.method(
                #getRoleCardTaskStatusApiRoleCardStatusTaskIdGet,
                [],
                {
                  #taskId: taskId,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i26.RoleCardTaskStatusResponse>>);

  @override
  _i8.Future<_i6.Response<_i27.SceneGalleryResponse>>
      getSceneGalleryApiSceneIllustrationGalleryTaskIdGet({
    required String? taskId,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getSceneGalleryApiSceneIllustrationGalleryTaskIdGet,
              [],
              {
                #taskId: taskId,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue:
                _i8.Future<_i6.Response<_i27.SceneGalleryResponse>>.value(
                    _FakeResponse_4<_i27.SceneGalleryResponse>(
              this,
              Invocation.method(
                #getSceneGalleryApiSceneIllustrationGalleryTaskIdGet,
                [],
                {
                  #taskId: taskId,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i27.SceneGalleryResponse>>);

  @override
  _i8.Future<_i6.Response<_i12.BuiltList<_i28.SourceSite>>>
      getSourceSitesSourceSitesGet({
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getSourceSitesSourceSitesGet,
              [],
              {
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue:
                _i8.Future<_i6.Response<_i12.BuiltList<_i28.SourceSite>>>.value(
                    _FakeResponse_4<_i12.BuiltList<_i28.SourceSite>>(
              this,
              Invocation.method(
                #getSourceSitesSourceSitesGet,
                [],
                {
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i12.BuiltList<_i28.SourceSite>>>);

  @override
  _i8.Future<_i6.Response<_i18.Uint8List>>
      getVideoFileApiImageToVideoVideoImgNameGet({
    required String? imgName,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getVideoFileApiImageToVideoVideoImgNameGet,
              [],
              {
                #imgName: imgName,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i18.Uint8List>>.value(
                _FakeResponse_4<_i18.Uint8List>(
              this,
              Invocation.method(
                #getVideoFileApiImageToVideoVideoImgNameGet,
                [],
                {
                  #imgName: imgName,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i18.Uint8List>>);

  @override
  _i8.Future<_i6.Response<_i12.BuiltMap<String, String>>> healthCheckHealthGet({
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #healthCheckHealthGet,
          [],
          {
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i8.Future<_i6.Response<_i12.BuiltMap<String, String>>>.value(
                _FakeResponse_4<_i12.BuiltMap<String, String>>(
          this,
          Invocation.method(
            #healthCheckHealthGet,
            [],
            {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<_i12.BuiltMap<String, String>>>);

  @override
  _i8.Future<_i6.Response<_i15.JsonObject>> indexGet({
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #indexGet,
          [],
          {
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<_i15.JsonObject>>.value(
            _FakeResponse_4<_i15.JsonObject>(
          this,
          Invocation.method(
            #indexGet,
            [],
            {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<_i15.JsonObject>>);

  @override
  _i8.Future<_i6.Response<_i29.SceneRegenerateResponse>>
      regenerateSceneImagesApiSceneIllustrationRegeneratePost({
    required _i30.SceneRegenerateRequest? sceneRegenerateRequest,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #regenerateSceneImagesApiSceneIllustrationRegeneratePost,
              [],
              {
                #sceneRegenerateRequest: sceneRegenerateRequest,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue:
                _i8.Future<_i6.Response<_i29.SceneRegenerateResponse>>.value(
                    _FakeResponse_4<_i29.SceneRegenerateResponse>(
              this,
              Invocation.method(
                #regenerateSceneImagesApiSceneIllustrationRegeneratePost,
                [],
                {
                  #sceneRegenerateRequest: sceneRegenerateRequest,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i29.SceneRegenerateResponse>>);

  @override
  _i8.Future<_i6.Response<_i15.JsonObject>>
      regenerateSimilarImagesApiRoleCardRegeneratePost({
    required _i31.RoleRegenerateRequest? roleRegenerateRequest,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #regenerateSimilarImagesApiRoleCardRegeneratePost,
              [],
              {
                #roleRegenerateRequest: roleRegenerateRequest,
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i15.JsonObject>>.value(
                _FakeResponse_4<_i15.JsonObject>(
              this,
              Invocation.method(
                #regenerateSimilarImagesApiRoleCardRegeneratePost,
                [],
                {
                  #roleRegenerateRequest: roleRegenerateRequest,
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i15.JsonObject>>);

  @override
  _i8.Future<_i6.Response<_i15.JsonObject>>
      roleCardHealthCheckApiRoleCardHealthGet({
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #roleCardHealthCheckApiRoleCardHealthGet,
              [],
              {
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i15.JsonObject>>.value(
                _FakeResponse_4<_i15.JsonObject>(
              this,
              Invocation.method(
                #roleCardHealthCheckApiRoleCardHealthGet,
                [],
                {
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i15.JsonObject>>);

  @override
  _i8.Future<_i6.Response<_i12.BuiltList<_i32.Novel>>> searchSearchGet({
    required String? keyword,
    String? sites,
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSearchGet,
          [],
          {
            #keyword: keyword,
            #sites: sites,
            #X_API_TOKEN: X_API_TOKEN,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i6.Response<_i12.BuiltList<_i32.Novel>>>.value(
            _FakeResponse_4<_i12.BuiltList<_i32.Novel>>(
          this,
          Invocation.method(
            #searchSearchGet,
            [],
            {
              #keyword: keyword,
              #sites: sites,
              #X_API_TOKEN: X_API_TOKEN,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i6.Response<_i12.BuiltList<_i32.Novel>>>);

  @override
  _i8.Future<_i6.Response<_i12.BuiltMap<String, _i15.JsonObject>>>
      securityCheckSecurityCheckGet({
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #securityCheckSecurityCheckGet,
              [],
              {
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<
                    _i6.Response<_i12.BuiltMap<String, _i15.JsonObject>>>.value(
                _FakeResponse_4<_i12.BuiltMap<String, _i15.JsonObject>>(
              this,
              Invocation.method(
                #securityCheckSecurityCheckGet,
                [],
                {
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8
              .Future<_i6.Response<_i12.BuiltMap<String, _i15.JsonObject>>>);

  @override
  _i8.Future<_i6.Response<_i15.JsonObject>>
      text2imgHealthCheckText2imgHealthGet({
    String? X_API_TOKEN,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #text2imgHealthCheckText2imgHealthGet,
              [],
              {
                #X_API_TOKEN: X_API_TOKEN,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i15.JsonObject>>.value(
                _FakeResponse_4<_i15.JsonObject>(
              this,
              Invocation.method(
                #text2imgHealthCheckText2imgHealthGet,
                [],
                {
                  #X_API_TOKEN: X_API_TOKEN,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i15.JsonObject>>);

  @override
  _i8.Future<_i6.Response<_i15.JsonObject>>
      uploadAppVersionApiAppVersionUploadPost({
    required _i7.MultipartFile? file,
    required String? version,
    required int? versionCode,
    String? X_API_TOKEN,
    String? changelog,
    bool? forceUpdate,
    _i9.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #uploadAppVersionApiAppVersionUploadPost,
              [],
              {
                #file: file,
                #version: version,
                #versionCode: versionCode,
                #X_API_TOKEN: X_API_TOKEN,
                #changelog: changelog,
                #forceUpdate: forceUpdate,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i8.Future<_i6.Response<_i15.JsonObject>>.value(
                _FakeResponse_4<_i15.JsonObject>(
              this,
              Invocation.method(
                #uploadAppVersionApiAppVersionUploadPost,
                [],
                {
                  #file: file,
                  #version: version,
                  #versionCode: versionCode,
                  #X_API_TOKEN: X_API_TOKEN,
                  #changelog: changelog,
                  #forceUpdate: forceUpdate,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i8.Future<_i6.Response<_i15.JsonObject>>);
}
