// Mocks generated by Mockito 5.4.6 from annotations
// in novel_app/test/unit/services/tts_player_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i17;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:novel_api/novel_api.dart' as _i4;
import 'package:novel_app/models/chapter.dart' as _i11;
import 'package:novel_app/models/character.dart' as _i3;
import 'package:novel_app/models/chat_scene.dart' as _i15;
import 'package:novel_app/models/novel.dart' as _i10;
import 'package:novel_app/models/outline.dart' as _i14;
import 'package:novel_app/models/scene_illustration.dart' as _i13;
import 'package:novel_app/models/search_result.dart' as _i12;
import 'package:novel_app/services/api_service_wrapper.dart' as _i16;
import 'package:novel_app/services/database_service.dart' as _i9;
import 'package:novel_app/services/tts_service.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCharacter_1 extends _i1.SmartFake implements _i3.Character {
  _FakeCharacter_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDefaultApi_2 extends _i1.SmartFake implements _i4.DefaultApi {
  _FakeDefaultApi_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_3 extends _i1.SmartFake implements _i5.Dio {
  _FakeDio_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageToVideoResponse_4 extends _i1.SmartFake
    implements _i4.ImageToVideoResponse {
  _FakeImageToVideoResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoStatusResponse_5 extends _i1.SmartFake
    implements _i4.VideoStatusResponse {
  _FakeVideoStatusResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModelsResponse_6 extends _i1.SmartFake
    implements _i4.ModelsResponse {
  _FakeModelsResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TtsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTtsService extends _i1.Mock implements _i6.TtsService {
  MockTtsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<bool> get isSpeaking => (super.noSuchMethod(
        Invocation.getter(#isSpeaking),
        returnValue: _i7.Stream<bool>.empty(),
      ) as _i7.Stream<bool>);

  @override
  _i7.Stream<String> get onSpeakComplete => (super.noSuchMethod(
        Invocation.getter(#onSpeakComplete),
        returnValue: _i7.Stream<String>.empty(),
      ) as _i7.Stream<String>);

  @override
  _i7.Stream<String> get onSpeakStart => (super.noSuchMethod(
        Invocation.getter(#onSpeakStart),
        returnValue: _i7.Stream<String>.empty(),
      ) as _i7.Stream<String>);

  @override
  _i7.Stream<String> get onError => (super.noSuchMethod(
        Invocation.getter(#onError),
        returnValue: _i7.Stream<String>.empty(),
      ) as _i7.Stream<String>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<bool> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<String> speak(String? text) => (super.noSuchMethod(
        Invocation.method(
          #speak,
          [text],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #speak,
            [text],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<void> pause() => (super.noSuchMethod(
        Invocation.method(
          #pause,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> resume() => (super.noSuchMethod(
        Invocation.method(
          #resume,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> stop() => (super.noSuchMethod(
        Invocation.method(
          #stop,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setSpeechRate(double? rate) => (super.noSuchMethod(
        Invocation.method(
          #setSpeechRate,
          [rate],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setPitch(double? pitch) => (super.noSuchMethod(
        Invocation.method(
          #setPitch,
          [pitch],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setVolume(double? volume) => (super.noSuchMethod(
        Invocation.method(
          #setVolume,
          [volume],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i6.TtsVoice>> getAvailableVoices() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableVoices,
          [],
        ),
        returnValue: _i7.Future<List<_i6.TtsVoice>>.value(<_i6.TtsVoice>[]),
      ) as _i7.Future<List<_i6.TtsVoice>>);

  @override
  _i7.Future<void> setVoice(String? voiceId) => (super.noSuchMethod(
        Invocation.method(
          #setVoice,
          [voiceId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i9.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isWebPlatform => (super.noSuchMethod(
        Invocation.getter(#isWebPlatform),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i7.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i7.Future<_i2.Database>);

  @override
  _i7.Future<int> addToBookshelf(_i10.Novel? novel) => (super.noSuchMethod(
        Invocation.method(
          #addToBookshelf,
          [novel],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> removeFromBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeFromBookshelf,
          [novelUrl],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i10.Novel>> getBookshelf() => (super.noSuchMethod(
        Invocation.method(
          #getBookshelf,
          [],
        ),
        returnValue: _i7.Future<List<_i10.Novel>>.value(<_i10.Novel>[]),
      ) as _i7.Future<List<_i10.Novel>>);

  @override
  _i7.Future<bool> isInBookshelf(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #isInBookshelf,
          [novelUrl],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<int> updateLastReadChapter(
    String? novelUrl,
    int? chapterIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastReadChapter,
          [
            novelUrl,
            chapterIndex,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> updateBackgroundSetting(
    String? novelUrl,
    String? backgroundSetting,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackgroundSetting,
          [
            novelUrl,
            backgroundSetting,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<String?> getBackgroundSetting(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackgroundSetting,
          [novelUrl],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<int> getLastReadChapter(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #getLastReadChapter,
          [novelUrl],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<bool> isChapterCached(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isChapterCached,
          [chapterUrl],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<String>> filterUncachedChapters(List<String>? chapterUrls) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterUncachedChapters,
          [chapterUrls],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  void markAsPreloading(String? chapterUrl) => super.noSuchMethod(
        Invocation.method(
          #markAsPreloading,
          [chapterUrl],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isPreloading(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #isPreloading,
          [chapterUrl],
        ),
        returnValue: false,
      ) as bool);

  @override
  void clearMemoryState() => super.noSuchMethod(
        Invocation.method(
          #clearMemoryState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<int> cacheChapter(
    String? novelUrl,
    _i11.Chapter? chapter,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheChapter,
          [
            novelUrl,
            chapter,
            content,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> updateChapterContent(
    String? chapterUrl,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChapterContent,
          [
            chapterUrl,
            content,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> deleteChapterCache(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteChapterCache,
          [chapterUrl],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<String?> getCachedChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapter,
          [chapterUrl],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<List<_i11.Chapter>> getCachedChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapters,
          [novelUrl],
        ),
        returnValue: _i7.Future<List<_i11.Chapter>>.value(<_i11.Chapter>[]),
      ) as _i7.Future<List<_i11.Chapter>>);

  @override
  _i7.Future<int> deleteCachedChapters(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteCachedChapters,
          [novelUrl],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> clearNovelCache(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #clearNovelCache,
          [novelUrl],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<Map<String, int>> getNovelCacheStats(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNovelCacheStats,
          [novelUrl],
        ),
        returnValue: _i7.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i7.Future<Map<String, int>>);

  @override
  _i7.Future<void> cacheWholeNovel(
    String? novelUrl,
    List<_i11.Chapter>? chapters,
    _i7.Future<String> Function(String)? getContent,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWholeNovel,
          [
            novelUrl,
            chapters,
            getContent,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> cacheNovelChapters(
    String? novelUrl,
    List<_i11.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheNovelChapters,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i11.Chapter>> getCachedNovelChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNovelChapters,
          [novelUrl],
        ),
        returnValue: _i7.Future<List<_i11.Chapter>>.value(<_i11.Chapter>[]),
      ) as _i7.Future<List<_i11.Chapter>>);

  @override
  _i7.Future<void> insertUserChapter(
    String? novelUrl,
    String? title,
    String? content,
    int? insertIndex,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertUserChapter,
          [
            novelUrl,
            title,
            content,
            insertIndex,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> createCustomNovel(
    String? title,
    String? author, {
    String? description,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomNovel,
          [
            title,
            author,
          ],
          {#description: description},
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> createCustomChapter(
    String? novelUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCustomChapter,
          [
            novelUrl,
            title,
            content,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> updateChaptersOrder(
    String? novelUrl,
    List<_i11.Chapter>? chapters,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChaptersOrder,
          [
            novelUrl,
            chapters,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getCustomChapterContent(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCustomChapterContent,
          [chapterUrl],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> updateCustomChapter(
    String? chapterUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCustomChapter,
          [
            chapterUrl,
            title,
            content,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteCustomChapter(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteCustomChapter,
          [chapterUrl],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i12.ChapterSearchResult>> searchInCachedContent(
    String? keyword, {
    String? novelUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchInCachedContent,
          [keyword],
          {#novelUrl: novelUrl},
        ),
        returnValue: _i7.Future<List<_i12.ChapterSearchResult>>.value(
            <_i12.ChapterSearchResult>[]),
      ) as _i7.Future<List<_i12.ChapterSearchResult>>);

  @override
  _i7.Future<List<_i12.CachedNovelInfo>> getCachedNovels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedNovels,
          [],
        ),
        returnValue: _i7.Future<List<_i12.CachedNovelInfo>>.value(
            <_i12.CachedNovelInfo>[]),
      ) as _i7.Future<List<_i12.CachedNovelInfo>>);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateNovelInBookshelf(_i10.Novel? novel) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNovelInBookshelf,
          [novel],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearBookshelfCache() => (super.noSuchMethod(
        Invocation.method(
          #clearBookshelfCache,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> getCachedChaptersCount(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChaptersCount,
          [novelUrl],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<_i11.Chapter?> getChapterByUrl(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapterByUrl,
          [chapterUrl],
        ),
        returnValue: _i7.Future<_i11.Chapter?>.value(),
      ) as _i7.Future<_i11.Chapter?>);

  @override
  _i7.Future<void> deleteUserChapter(String? chapterUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteUserChapter,
          [chapterUrl],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateReadingProgress(
    String? novelUrl,
    int? chapterIndex,
    double? progress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReadingProgress,
          [
            novelUrl,
            chapterIndex,
            progress,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<int> createCharacter(_i3.Character? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCharacter,
          [character],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i3.Character>> getCharacters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacters,
          [novelUrl],
        ),
        returnValue: _i7.Future<List<_i3.Character>>.value(<_i3.Character>[]),
      ) as _i7.Future<List<_i3.Character>>);

  @override
  _i7.Future<_i3.Character?> getCharacter(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getCharacter,
          [id],
        ),
        returnValue: _i7.Future<_i3.Character?>.value(),
      ) as _i7.Future<_i3.Character?>);

  @override
  _i7.Future<int> updateCharacter(_i3.Character? character) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacter,
          [character],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> deleteCharacter(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCharacter,
          [id],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<_i3.Character?> findCharacterByName(
    String? novelUrl,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCharacterByName,
          [
            novelUrl,
            name,
          ],
        ),
        returnValue: _i7.Future<_i3.Character?>.value(),
      ) as _i7.Future<_i3.Character?>);

  @override
  _i7.Future<_i3.Character> updateOrInsertCharacter(
          _i3.Character? newCharacter) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrInsertCharacter,
          [newCharacter],
        ),
        returnValue: _i7.Future<_i3.Character>.value(_FakeCharacter_1(
          this,
          Invocation.method(
            #updateOrInsertCharacter,
            [newCharacter],
          ),
        )),
      ) as _i7.Future<_i3.Character>);

  @override
  _i7.Future<List<_i3.Character>> batchUpdateCharacters(
          List<_i3.Character>? newCharacters) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateCharacters,
          [newCharacters],
        ),
        returnValue: _i7.Future<List<_i3.Character>>.value(<_i3.Character>[]),
      ) as _i7.Future<List<_i3.Character>>);

  @override
  _i7.Future<List<String>> getCharacterNames(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterNames,
          [novelUrl],
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);

  @override
  _i7.Future<bool> characterExists(int? id) => (super.noSuchMethod(
        Invocation.method(
          #characterExists,
          [id],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<List<_i3.Character>> getCharactersByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharactersByIds,
          [ids],
        ),
        returnValue: _i7.Future<List<_i3.Character>>.value(<_i3.Character>[]),
      ) as _i7.Future<List<_i3.Character>>);

  @override
  _i7.Future<int> deleteAllCharacters(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllCharacters,
          [novelUrl],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> updateCharacterCachedImage(
    int? characterId,
    String? imageUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterCachedImage,
          [
            characterId,
            imageUrl,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> clearCharacterCachedImage(int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearCharacterCachedImage,
          [characterId],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> clearAllCharacterCachedImages(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearAllCharacterCachedImages,
          [novelUrl],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i11.Chapter>> getChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapters,
          [novelUrl],
        ),
        returnValue: _i7.Future<List<_i11.Chapter>>.value(<_i11.Chapter>[]),
      ) as _i7.Future<List<_i11.Chapter>>);

  @override
  _i7.Future<void> markChapterAsRead(
    String? novelUrl,
    String? chapterUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markChapterAsRead,
          [
            novelUrl,
            chapterUrl,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String> getChapterContent(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapterContent,
          [chapterUrl],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getChapterContent,
            [chapterUrl],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String> getCachedChapterContent(String? chapterUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedChapterContent,
          [chapterUrl],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getCachedChapterContent,
            [chapterUrl],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<String?> getCharacterCachedImage(int? characterId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCharacterCachedImage,
          [characterId],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<int> updateCharacterAvatar(
    int? characterId, {
    String? imageUrl,
    String? originalFilename,
    String? originalImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCharacterAvatar,
          [characterId],
          {
            #imageUrl: imageUrl,
            #originalFilename: originalFilename,
            #originalImageUrl: originalImageUrl,
          },
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<bool> hasCharacterAvatar(int? characterId) => (super.noSuchMethod(
        Invocation.method(
          #hasCharacterAvatar,
          [characterId],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<int> insertSceneIllustration(
          _i13.SceneIllustration? illustration) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertSceneIllustration,
          [illustration],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> updateSceneIllustrationStatus(
    int? id,
    String? status, {
    List<String>? images,
    String? prompts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSceneIllustrationStatus,
          [
            id,
            status,
          ],
          {
            #images: images,
            #prompts: prompts,
          },
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i13.SceneIllustration>> getSceneIllustrationsByChapter(
    String? novelUrl,
    String? chapterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationsByChapter,
          [
            novelUrl,
            chapterId,
          ],
        ),
        returnValue: _i7.Future<List<_i13.SceneIllustration>>.value(
            <_i13.SceneIllustration>[]),
      ) as _i7.Future<List<_i13.SceneIllustration>>);

  @override
  _i7.Future<_i13.SceneIllustration?> getSceneIllustrationByTaskId(
          String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationByTaskId,
          [taskId],
        ),
        returnValue: _i7.Future<_i13.SceneIllustration?>.value(),
      ) as _i7.Future<_i13.SceneIllustration?>);

  @override
  _i7.Future<Map<String, dynamic>> getSceneIllustrationsPaginated({
    required int? page,
    required int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationsPaginated,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<int> deleteSceneIllustration(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSceneIllustration,
          [id],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> deleteSceneIllustrationsByChapter(
    String? novelUrl,
    String? chapterId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSceneIllustrationsByChapter,
          [
            novelUrl,
            chapterId,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i13.SceneIllustration>> getPendingSceneIllustrations() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingSceneIllustrations,
          [],
        ),
        returnValue: _i7.Future<List<_i13.SceneIllustration>>.value(
            <_i13.SceneIllustration>[]),
      ) as _i7.Future<List<_i13.SceneIllustration>>);

  @override
  _i7.Future<int> batchUpdateSceneIllustrations(
    List<int>? ids,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdateSceneIllustrations,
          [
            ids,
            status,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> saveOutline(_i14.Outline? outline) => (super.noSuchMethod(
        Invocation.method(
          #saveOutline,
          [outline],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<_i14.Outline?> getOutlineByNovelUrl(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOutlineByNovelUrl,
          [novelUrl],
        ),
        returnValue: _i7.Future<_i14.Outline?>.value(),
      ) as _i7.Future<_i14.Outline?>);

  @override
  _i7.Future<List<_i14.Outline>> getAllOutlines() => (super.noSuchMethod(
        Invocation.method(
          #getAllOutlines,
          [],
        ),
        returnValue: _i7.Future<List<_i14.Outline>>.value(<_i14.Outline>[]),
      ) as _i7.Future<List<_i14.Outline>>);

  @override
  _i7.Future<int> deleteOutline(String? novelUrl) => (super.noSuchMethod(
        Invocation.method(
          #deleteOutline,
          [novelUrl],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> updateOutlineContent(
    String? novelUrl,
    String? title,
    String? content,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOutlineContent,
          [
            novelUrl,
            title,
            content,
          ],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> insertChatScene(_i15.ChatScene? scene) => (super.noSuchMethod(
        Invocation.method(
          #insertChatScene,
          [scene],
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<void> updateChatScene(_i15.ChatScene? scene) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateChatScene,
          [scene],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteChatScene(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteChatScene,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i15.ChatScene>> getAllChatScenes() => (super.noSuchMethod(
        Invocation.method(
          #getAllChatScenes,
          [],
        ),
        returnValue: _i7.Future<List<_i15.ChatScene>>.value(<_i15.ChatScene>[]),
      ) as _i7.Future<List<_i15.ChatScene>>);

  @override
  _i7.Future<_i15.ChatScene?> getChatSceneById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getChatSceneById,
          [id],
        ),
        returnValue: _i7.Future<_i15.ChatScene?>.value(),
      ) as _i7.Future<_i15.ChatScene?>);

  @override
  _i7.Future<List<_i15.ChatScene>> searchChatScenes(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchChatScenes,
          [query],
        ),
        returnValue: _i7.Future<List<_i15.ChatScene>>.value(<_i15.ChatScene>[]),
      ) as _i7.Future<List<_i15.ChatScene>>);
}

/// A class which mocks [ApiServiceWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServiceWrapper extends _i1.Mock implements _i16.ApiServiceWrapper {
  MockApiServiceWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DefaultApi get defaultApi => (super.noSuchMethod(
        Invocation.getter(#defaultApi),
        returnValue: _FakeDefaultApi_2(
          this,
          Invocation.getter(#defaultApi),
        ),
      ) as _i4.DefaultApi);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_3(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i5.Dio);

  @override
  _i7.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  Map<String, dynamic> getInitStatus() => (super.noSuchMethod(
        Invocation.method(
          #getInitStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i7.Future<String?> getHost() => (super.noSuchMethod(
        Invocation.method(
          #getHost,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> setConfig({
    required String? host,
    String? token,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setConfig,
          [],
          {
            #host: host,
            #token: token,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i10.Novel>> searchNovels(
    String? keyword, {
    List<String>? sites,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchNovels,
          [keyword],
          {#sites: sites},
        ),
        returnValue: _i7.Future<List<_i10.Novel>>.value(<_i10.Novel>[]),
      ) as _i7.Future<List<_i10.Novel>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getSourceSites() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSourceSites,
          [],
        ),
        returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<_i11.Chapter>> getChapters(String? novelUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapters,
          [novelUrl],
        ),
        returnValue: _i7.Future<List<_i11.Chapter>>.value(<_i11.Chapter>[]),
      ) as _i7.Future<List<_i11.Chapter>>);

  @override
  _i7.Future<String> getChapterContent(
    String? chapterUrl, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChapterContent,
          [chapterUrl],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getChapterContent,
            [chapterUrl],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i7.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<Map<String, dynamic>> generateRoleCardImages({
    required String? roleId,
    required Map<String, dynamic>? roles,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateRoleCardImages,
          [],
          {
            #roleId: roleId,
            #roles: roles,
            #modelName: modelName,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getRoleGallery(String? roleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoleGallery,
          [roleId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<bool> deleteRoleImage({
    required String? roleId,
    required String? imageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRoleImage,
          [],
          {
            #roleId: roleId,
            #imageUrl: imageUrl,
          },
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, dynamic>> generateMoreImages({
    required String? roleId,
    required int? count,
    String? referenceImageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateMoreImages,
          [],
          {
            #roleId: roleId,
            #count: count,
            #referenceImageUrl: referenceImageUrl,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> createSceneIllustration({
    required String? chaptersContent,
    required String? taskId,
    required dynamic roles,
    required int? num,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSceneIllustration,
          [],
          {
            #chaptersContent: chaptersContent,
            #taskId: taskId,
            #roles: roles,
            #num: num,
            #modelName: modelName,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> getSceneIllustrationGallery(
          String? taskId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSceneIllustrationGallery,
          [taskId],
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> deleteSceneIllustrationImage({
    required String? taskId,
    required String? filename,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSceneIllustrationImage,
          [],
          {
            #taskId: taskId,
            #filename: filename,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> regenerateSceneIllustration({
    required String? taskId,
    required int? count,
    String? model,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #regenerateSceneIllustration,
          [],
          {
            #taskId: taskId,
            #count: count,
            #model: model,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i17.Uint8List> getImageProxy(String? filename) =>
      (super.noSuchMethod(
        Invocation.method(
          #getImageProxy,
          [filename],
        ),
        returnValue: _i7.Future<_i17.Uint8List>.value(_i17.Uint8List(0)),
      ) as _i7.Future<_i17.Uint8List>);

  @override
  _i7.Future<_i4.ImageToVideoResponse> generateVideoFromImage({
    required String? imgName,
    required String? userInput,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateVideoFromImage,
          [],
          {
            #imgName: imgName,
            #userInput: userInput,
            #modelName: modelName,
          },
        ),
        returnValue: _i7.Future<_i4.ImageToVideoResponse>.value(
            _FakeImageToVideoResponse_4(
          this,
          Invocation.method(
            #generateVideoFromImage,
            [],
            {
              #imgName: imgName,
              #userInput: userInput,
              #modelName: modelName,
            },
          ),
        )),
      ) as _i7.Future<_i4.ImageToVideoResponse>);

  @override
  _i7.Future<_i4.VideoStatusResponse> checkVideoStatus(String? imgName) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkVideoStatus,
          [imgName],
        ),
        returnValue: _i7.Future<_i4.VideoStatusResponse>.value(
            _FakeVideoStatusResponse_5(
          this,
          Invocation.method(
            #checkVideoStatus,
            [imgName],
          ),
        )),
      ) as _i7.Future<_i4.VideoStatusResponse>);

  @override
  _i7.Future<String> getVideoFileUrl(String? imgName) => (super.noSuchMethod(
        Invocation.method(
          #getVideoFileUrl,
          [imgName],
        ),
        returnValue: _i7.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #getVideoFileUrl,
            [imgName],
          ),
        )),
      ) as _i7.Future<String>);

  @override
  _i7.Future<Map<String, dynamic>> regenerateSceneIllustrationImages({
    required String? taskId,
    required int? count,
    String? modelName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #regenerateSceneIllustrationImages,
          [],
          {
            #taskId: taskId,
            #count: count,
            #modelName: modelName,
          },
        ),
        returnValue:
            _i7.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i4.ModelsResponse> getModels() => (super.noSuchMethod(
        Invocation.method(
          #getModels,
          [],
        ),
        returnValue: _i7.Future<_i4.ModelsResponse>.value(_FakeModelsResponse_6(
          this,
          Invocation.method(
            #getModels,
            [],
          ),
        )),
      ) as _i7.Future<_i4.ModelsResponse>);

  @override
  _i7.Future<List<String>> getModelTitles({String? apiType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModelTitles,
          [],
          {#apiType: apiType},
        ),
        returnValue: _i7.Future<List<String>>.value(<String>[]),
      ) as _i7.Future<List<String>>);
}
